import type { ReviewedQuestion } from "@/lib/quiz/content/types";
import { defineChoices, defineQuestion } from "@/lib/quiz/content/questions/helpers";

const sourceId = "source_engineering_fundamentals";

export const csFoundationsQuestions: ReviewedQuestion[] = [
  defineQuestion({
    id: "q_cs_01",
    categoryId: "cs_foundations",
    subtopicId: "data_structures",
    conceptId: "concept_cs_fifo_job_queue",
    sourceId,
    scenario: "A worker must process accepted jobs in arrival order. Jobs are appended continuously, and undo is not required.",
    caseType: "basic_application",
    decisionCriteria: ["Preserve first-in, first-out processing with constant-time insertion and removal."],
    practicalNotes: ["Use a durable queue rather than an in-memory queue when jobs must survive a process restart."],
    checkQuestion: "Would the choice change if the newest job had to run first?",
    prompt: "Which data structure best matches the worker's ordering requirement?",
    choices: defineChoices("a", [
      ["A queue", "A queue removes the oldest enqueued job first.", "Jobs run in accepted order without shifting an array."],
      ["A stack", "A stack removes the newest job first, reversing the required order.", "Older jobs can wait indefinitely during steady arrivals."],
      ["A set", "A set supports membership, not a defined dequeue order.", "The worker cannot reliably choose the next accepted job."],
      ["A binary search tree", "A tree orders by a key rather than arrival time unless extra sequencing is added.", "The design adds comparison and balancing work without meeting FIFO directly."],
    ]),
    difficulty: "beginner",
    rationale: "The only stated ordering rule is arrival order, so FIFO queue operations match both sequencing and append/remove cost.",
  }),
  defineQuestion({
    id: "q_cs_02",
    categoryId: "cs_foundations",
    subtopicId: "data_structures",
    conceptId: "concept_cs_membership_lookup",
    sourceId,
    scenario: "A service checks 200,000 opaque user IDs for membership 50,000 times per second. It has enough memory for an additional hash table, and iteration order is irrelevant.",
    caseType: "design_tradeoff",
    decisionCriteria: ["Prioritize average lookup latency; accept extra memory and hash maintenance."],
    practicalNotes: ["Measure real key distribution because adversarial collisions can degrade a hash table."],
    checkQuestion: "What resource cost buys the lower lookup latency?",
    prompt: "Which representation should replace the current linear array scan?",
    choices: defineChoices("c", [
      ["Keep the array and scan it", "A scan remains O(n) for each membership check.", "CPU cost grows directly with the number of stored IDs."],
      ["Build a hash set", "A hash set gives average O(1) membership checks under the stated memory budget.", "Reads become much cheaper while memory and update work increase."],
      ["Sort the array before every lookup", "Sorting per request costs more than the existing scan.", "Latency increases sharply and repeated work is wasted."],
      ["Store IDs in a linked list", "A linked list still requires O(n) traversal and has poor cache locality.", "The service uses extra pointers without improving membership latency."],
    ], "b"),
    difficulty: "intermediate",
    rationale: "Frequent membership checks dominate this workload, and the explicit memory headroom makes the hash set's average constant-time lookup the intended trade-off.",
  }),
  defineQuestion({
    id: "q_cs_03",
    categoryId: "cs_foundations",
    subtopicId: "algorithms",
    conceptId: "concept_cs_complexity_growth",
    sourceId,
    scenario: "A nightly task will grow from 10,000 to 10,000,000 records. It must complete within one hour, so an implementation whose work scales linearly or near-linearly is required.",
    caseType: "basic_application",
    decisionCriteria: ["Choose the smallest growth rate that still solves the task under a thousand-fold input increase."],
    practicalNotes: ["Constants still matter, but a quadratic path is not rescued by small benchmark constants at this scale."],
    checkQuestion: "How does a thousand-fold input increase affect a quadratic implementation?",
    prompt: "Which measured complexity is acceptable for the production path?",
    choices: defineChoices("b", [
      ["O(n²)", "Quadratic work grows by roughly one million times when input grows one thousand times.", "The nightly task will exceed the deadline as data approaches the forecast."],
      ["O(2ⁿ)", "Exponential work becomes infeasible far before ten million records.", "The process will not complete for production-sized input."],
      ["O(n log n)", "Near-linear growth is consistent with sorting or indexed aggregation at the forecast size.", "The implementation has a plausible path to the one-hour budget after benchmarking."],
      ["O(n³)", "Cubic work grows even faster than the rejected quadratic option.", "Runtime becomes dominated by input growth rather than available compute."],
    ], "c"),
    difficulty: "beginner",
    rationale: "Among the choices, O(n log n) is the only growth rate compatible with the explicit near-linear requirement at ten million records.",
  }),
  defineQuestion({
    id: "q_cs_04",
    categoryId: "cs_foundations",
    subtopicId: "algorithms",
    conceptId: "concept_cs_accidental_quadratic",
    sourceId,
    scenario: "Importing n rows loops over every row and calls existingIds.includes(id) on an n-item array. Profiling shows the includes calls dominate at 100,000 rows.",
    artifacts: [{
      kind: "code",
      title: "Import hot path",
      language: "typescript",
      content: "type Row = { id: string };\ndeclare const rows: Row[];\ndeclare const existingIds: string[];\ndeclare function insert(row: Row): void;\n\nfor (const row of rows) {\n  if (!existingIds.includes(row.id)) insert(row);\n}",
    }],
    caseType: "debugging_performance",
    decisionCriteria: ["Remove the nested linear membership scan without changing duplicate semantics."],
    practicalNotes: ["Build the lookup structure once outside the loop and update it after each accepted insertion."],
    checkQuestion: "Which operation is repeated n times and itself scans up to n elements?",
    prompt: "What change directly removes the accidental O(n²) behavior?",
    choices: defineChoices("a", [
      ["Run the loop in a Promise.all", "Concurrency does not change the number of linear array scans.", "The database sees more simultaneous work while CPU complexity remains quadratic."],
      ["Sort rows after all inserts", "Post-insert sorting does not accelerate membership checks inside the loop.", "Duplicate checks remain the dominant hot path."],
      ["Replace includes with find", "Array.find is also a linear scan.", "The syntax changes but asymptotic work does not."],
      ["Create a Set from existingIds and call has", "Set.has replaces each linear scan with average constant-time membership.", "The hot path becomes approximately O(n) plus one-time set construction."],
    ], "d"),
    difficulty: "intermediate",
    rationale: "The profiler identifies n repeated O(n) includes calls; constructing one Set removes that inner scan while preserving membership behavior.",
  }),
  defineQuestion({
    id: "q_cs_05",
    categoryId: "cs_foundations",
    subtopicId: "operating_systems",
    conceptId: "concept_cs_io_concurrency",
    sourceId,
    scenario: "A Node.js endpoint waits on 40 independent network calls averaging 200 ms each. CPU usage is below 10%, and responses can be combined only after all calls finish.",
    caseType: "design_tradeoff",
    decisionCriteria: ["Overlap blocking I/O without introducing CPU worker overhead."],
    practicalNotes: ["Bound concurrency if the upstream has connection or rate limits."],
    checkQuestion: "Would worker threads help if profiling instead showed sustained CPU saturation?",
    prompt: "Which concurrency approach most directly reduces endpoint latency?",
    choices: defineChoices("d", [
      ["Issue bounded asynchronous requests concurrently", "The waits can overlap because the work is I/O-bound and independent.", "Latency approaches the slowest batches rather than the sum of all waits."],
      ["Move every request into a CPU worker thread", "Worker threads target CPU-bound work and add messaging overhead here.", "Complexity increases without reducing network wait time."],
      ["Make the requests sequential to protect the event loop", "Awaiting network I/O does not consume the event loop CPU while waiting.", "Latency remains near forty times the average call time."],
      ["Increase the process priority", "Scheduler priority cannot shorten upstream network latency.", "The endpoint still spends nearly all time waiting on remote systems."],
    ], "a"),
    difficulty: "intermediate",
    rationale: "Low CPU and independent network waits identify an I/O-bound workload, so asynchronous overlap is the direct lever while bounded concurrency protects the upstream.",
  }),
  defineQuestion({
    id: "q_cs_06",
    categoryId: "cs_foundations",
    subtopicId: "operating_systems",
    conceptId: "concept_cs_process_isolation",
    sourceId,
    scenario: "Four worker processes increment a normal in-memory counter, but the dashboard shows different totals per worker after restarts. The total must be consistent across processes and survive crashes.",
    caseType: "common_failure",
    decisionCriteria: ["Use shared durable state with atomic increments across isolated processes."],
    practicalNotes: ["Expose update failures rather than silently falling back to a per-process counter."],
    checkQuestion: "Why can one process not read another process's ordinary heap value?",
    prompt: "Where should the counter be maintained?",
    choices: defineChoices("b", [
      ["In a module-level variable in each worker", "Each process owns a separate address space.", "Totals diverge and reset independently on restart."],
      ["In a durable shared store with an atomic increment", "A database or equivalent service coordinates updates across process boundaries.", "All workers observe one crash-resistant total."],
      ["In a closure around the request handler", "A closure is still local to one process and may be recreated.", "The same isolation and restart loss remain."],
      ["In a larger per-process heap", "More memory does not create shared state.", "Capacity rises but correctness does not improve."],
    ]),
    difficulty: "beginner",
    rationale: "Process isolation explains the divergent heaps, and the durability requirement rules out any in-memory per-worker representation.",
  }),
  defineQuestion({
    id: "q_cs_07",
    categoryId: "cs_foundations",
    subtopicId: "networking",
    conceptId: "concept_cs_retry_packet_loss",
    sourceId,
    scenario: "A read-only RPC occasionally times out during 1% packet loss. The service has a 900 ms deadline, typical latency is 80 ms, and simultaneous immediate retries have overloaded the upstream before.",
    caseType: "maintainability_safety",
    decisionCriteria: ["Retry only within the deadline, avoid synchronized retry bursts, and keep the operation safe to repeat."],
    practicalNotes: ["Record attempt count and remaining deadline to distinguish recovery from retry amplification."],
    checkQuestion: "Why is jitter important when many clients see the same transient failure?",
    prompt: "Which retry policy best fits these constraints?",
    choices: defineChoices("c", [
      ["Retry forever at a fixed 10 ms interval", "Unbounded rapid retries ignore the caller deadline.", "Packet loss turns into sustained upstream overload."],
      ["Never retry any timeout", "A transient lost packet can be recovered safely for this read-only operation.", "The service exposes avoidable failures despite ample deadline."],
      ["Retry a small bounded number with exponential backoff and jitter", "Bounded jittered backoff uses the remaining deadline and desynchronizes clients.", "Transient loss can recover without creating a retry storm."],
      ["Send ten identical requests immediately and take the first", "Aggressive hedging multiplies load for every timeout.", "The upstream can fail under the added burst."],
    ]),
    difficulty: "intermediate",
    rationale: "The operation is repeatable and the deadline allows another attempt, while the prior overload makes bounded exponential backoff with jitter essential.",
  }),
  defineQuestion({
    id: "q_cs_08",
    categoryId: "cs_foundations",
    subtopicId: "networking",
    conceptId: "concept_cs_protocol_layer_diagnosis",
    sourceId,
    scenario: "dig returns the expected IP and TCP port 443 accepts connections, but the client reports CERTIFICATE_VERIFY_FAILED before any HTTP status is logged.",
    caseType: "common_failure",
    decisionCriteria: ["Diagnose the earliest failing protocol layer using the observed evidence."],
    practicalNotes: ["Inspect certificate hostname, chain, validity period, and client trust store before changing HTTP handlers."],
    checkQuestion: "Which successful checks rule out DNS and basic TCP reachability?",
    prompt: "Which layer should be investigated first?",
    choices: defineChoices("a", [
      ["The application HTTP route", "No HTTP response exists because the failure occurs before an HTTP exchange.", "Handler changes cannot affect certificate verification."],
      ["DNS resolution", "The expected address was already returned.", "Changing DNS risks redirecting working traffic without addressing the error."],
      ["TCP connection establishment", "The client successfully connects to port 443.", "Network firewall changes do not fix certificate trust."],
      ["The TLS certificate and trust chain", "Certificate verification is a TLS handshake step before HTTP.", "Correcting hostname, chain, expiry, or trust store can allow the request to proceed."],
    ], "d"),
    difficulty: "intermediate",
    rationale: "Successful DNS and TCP checks plus a certificate verification error before HTTP isolate the failure to the TLS layer.",
  }),
  defineQuestion({
    id: "q_cs_09",
    categoryId: "cs_foundations",
    subtopicId: "databases",
    conceptId: "concept_cs_orders_composite_index",
    sourceId: "source_mysql_docs",
    scenario: "The orders table has 50 million rows across 4,000 tenants. This query is frequent; each tenant has many statuses, and the UI needs its newest 50 orders.",
    artifacts: [{
      kind: "sql",
      title: "Orders query",
      language: "sql",
      content: "SELECT id, status, created_at\nFROM orders\nWHERE tenant_id = ?\nORDER BY created_at DESC\nLIMIT 50;",
    }],
    caseType: "debugging_performance",
    decisionCriteria: ["Match the equality predicate first, then support ordered retrieval without a filesort."],
    practicalNotes: ["Confirm the chosen index with EXPLAIN and production-like tenant cardinality."],
    checkQuestion: "Why must tenant_id precede created_at for this query pattern?",
    prompt: "Which index best supports the query while avoiding a global created_at scan?",
    choices: defineChoices("b", [
      ["INDEX (tenant_id, created_at DESC)", "The equality prefix narrows one tenant and the next column supplies the required order.", "The database can read the newest tenant rows directly and stop after 50."],
      ["INDEX (created_at DESC, tenant_id)", "The leading timestamp orders all tenants before filtering tenant_id.", "The engine may scan many unrelated recent orders."],
      ["INDEX (status, tenant_id)", "Status is neither filtered nor sorted in the query.", "The index does not provide the required access path."],
      ["Separate indexes on tenant_id and created_at", "Index merge does not generally preserve the composite ordering needed here.", "Extra reads or a filesort remain likely."],
    ], "a"),
    difficulty: "advanced",
    rationale: "The composite index follows the query: tenant_id is the selective equality prefix and created_at supplies descending order for an early LIMIT stop.",
  }),
  defineQuestion({
    id: "q_cs_10",
    categoryId: "cs_foundations",
    subtopicId: "databases",
    conceptId: "concept_cs_write_heavy_indexes",
    sourceId: "source_mysql_docs",
    scenario: "An event table receives 80,000 inserts per second. Ten single-column indexes exist, but production reads use only event_id and occurred_at; storage and write latency are over budget.",
    caseType: "maintainability_safety",
    decisionCriteria: ["Retain indexes proven by read paths while reducing per-insert maintenance and storage."],
    practicalNotes: ["Use query statistics and a staged drop so an overlooked read can be detected and restored."],
    checkQuestion: "What cost does every additional B-tree impose on each insert?",
    prompt: "What is the safest corrective action?",
    choices: defineChoices("d", [
      ["Add indexes for every remaining column", "More indexes increase write amplification and storage.", "Insert latency and capacity pressure worsen."],
      ["Measure usage, then remove unused indexes in a staged rollout", "Index usage evidence protects required reads while targeting unnecessary write work.", "Writes become cheaper and rollback remains possible if a query regresses."],
      ["Drop the primary event_id index first", "The primary lookup is explicitly used by production reads.", "Core reads regress and row identity constraints may be lost."],
      ["Disable durability for faster inserts", "Durability is unrelated to whether unused indexes are maintained.", "Crash loss risk rises while avoidable index overhead remains."],
    ], "b"),
    difficulty: "advanced",
    rationale: "The workload is write-bound and only two access paths are observed, so evidence-led staged removal addresses index maintenance without guessing about read safety.",
  }),
];
