import type { ReviewedQuestion } from "@/lib/quiz/content/types";
import { defineChoices, defineQuestion } from "@/lib/quiz/content/questions/helpers";

const webSourceId = "source_mdndocs_web";
const tsSourceId = "source_typescript_handbook";

export const frontendQuestions: ReviewedQuestion[] = [
  defineQuestion({
    id: "q_front_01",
    categoryId: "frontend",
    subtopicId: "typescript",
    conceptId: "concept_front_satisfies_inference",
    sourceId: tsSourceId,
    scenario: "A route table must contain only valid paths, while each key's literal path must remain available to downstream generic code.",
    artifacts: [{
      kind: "code",
      title: "Typed route table",
      language: "typescript",
      content: "type RouteTable = Record<string, `/${string}`>;\n\nconst routes = {\n  home: \"/\",\n  account: \"/account\",\n} satisfies RouteTable;\n\nconst accountPath: \"/account\" = routes.account;",
    }],
    caseType: "basic_application",
    decisionCriteria: ["Check the object shape without widening its property values to the target index signature."],
    practicalNotes: ["Use satisfies for conformance; use an annotation when intentional widening is desired."],
    checkQuestion: "What literal type does routes.account retain?",
    prompt: "Why is satisfies preferable to annotating routes as RouteTable here?",
    choices: defineChoices("b", [
      ["It validates the paths at runtime", "satisfies is erased and adds no runtime validator.", "Untrusted runtime input still requires explicit validation."],
      ["It checks RouteTable compatibility while preserving literal inference", "The object is checked, but its own specific inferred property types remain.", "Generic consumers retain the literal \"/account\" value."],
      ["It makes every route property optional", "satisfies does not alter optionality.", "Missing required properties would still be checked by the target type."],
      ["It suppresses excess-property errors", "satisfies performs compatibility checks rather than disabling them.", "Misspelled or invalid values remain visible to the compiler."],
    ]),
    difficulty: "intermediate",
    rationale: "The artifact needs both conformance to slash-prefixed paths and the specific \"/account\" type; satisfies supplies exactly that combination.",
  }),
  defineQuestion({
    id: "q_front_02",
    categoryId: "frontend",
    subtopicId: "typescript",
    conceptId: "concept_front_unsafe_assertion",
    sourceId: tsSourceId,
    scenario: "JSON.parse returns unknown data from a third-party endpoint. The endpoint may omit id or send id as a number, but renderUser requires a string id.",
    artifacts: [{
      kind: "code",
      title: "Unsafe boundary",
      language: "typescript",
      content: "type User = { id: string; name: string };\nconst payload: unknown = JSON.parse(body);\nrenderUser(payload as User);",
    }],
    caseType: "common_failure",
    decisionCriteria: ["Establish the runtime shape before granting the trusted User type."],
    practicalNotes: ["Keep parsing at the network boundary and return structured validation errors."],
    checkQuestion: "What runtime check does the as assertion perform?",
    prompt: "What should replace the direct assertion?",
    choices: defineChoices("d", [
      ["Use payload as unknown as User", "A double assertion bypasses even more compiler compatibility checks.", "Malformed data still reaches renderUser."],
      ["Change User.id to any", "any removes useful guarantees throughout the application.", "Type errors propagate beyond the boundary."],
      ["Validate payload with a runtime schema before returning User", "Runtime validation proves required fields and types before trusted use.", "Malformed responses are rejected at the boundary."],
      ["Add a non-null assertion to payload", "Non-null says nothing about object fields or id type.", "Numbers and missing fields still pass into rendering."],
    ], "c"),
    difficulty: "intermediate",
    rationale: "The input is untrusted at runtime and TypeScript assertions emit no checks, so only boundary validation can justify treating the value as User.",
  }),
  defineQuestion({
    id: "q_front_03",
    categoryId: "frontend",
    subtopicId: "browsers",
    conceptId: "concept_front_main_thread_long_task",
    sourceId: webSourceId,
    scenario: "Typing freezes for 700 ms after each keypress. A performance trace shows one synchronous JavaScript task parsing and sorting 200,000 rows on the main thread; network time is 20 ms.",
    caseType: "debugging_performance",
    decisionCriteria: ["Remove long CPU work from the main interaction path; network optimization is not the bottleneck."],
    practicalNotes: ["First reduce work and memoize; use a Web Worker when the remaining CPU task is large and transferable."],
    checkQuestion: "Which trace evidence identifies the browser main thread as the bottleneck?",
    prompt: "Which change most directly restores input responsiveness?",
    choices: defineChoices("c", [
      ["Increase the HTTP cache lifetime", "The trace shows only 20 ms of network time.", "The 700 ms JavaScript task remains."],
      ["Add more CSS containment", "Layout is not identified as the long task.", "Parsing and sorting still block input."],
      ["Run the same work in another microtask", "Microtasks still execute on the main thread before rendering and input.", "The freeze is merely rescheduled."],
      ["Move the heavy transform to a Web Worker and render a bounded result", "Worker CPU does not block the browser main thread.", "Keystrokes remain responsive while computation proceeds."],
    ], "d"),
    difficulty: "intermediate",
    rationale: "The profile isolates a synchronous CPU long task on the main thread, so off-thread computation plus bounded rendering addresses the measured cause.",
  }),
  defineQuestion({
    id: "q_front_04",
    categoryId: "frontend",
    subtopicId: "browsers",
    conceptId: "concept_front_sensitive_browser_state",
    sourceId: webSourceId,
    scenario: "A same-site app needs a session credential sent automatically to its backend. Page JavaScript never needs to read the credential, and XSS theft impact must be reduced.",
    caseType: "maintainability_safety",
    decisionCriteria: ["Prevent JavaScript credential reads while using browser-managed request attachment."],
    practicalNotes: ["HttpOnly does not stop CSRF; combine it with Secure, SameSite, and request-level CSRF controls."],
    checkQuestion: "Which browser storage is deliberately unreadable to JavaScript?",
    prompt: "Where should the session identifier be stored?",
    choices: defineChoices("b", [
      ["A Secure HttpOnly cookie", "HttpOnly blocks document access while the browser can attach the cookie to matching requests.", "Common token-exfiltration scripts cannot directly read the session ID."],
      ["localStorage", "Any script executing in the origin can read localStorage.", "An XSS can copy the bearer credential."],
      ["sessionStorage", "sessionStorage is also readable by page JavaScript.", "Tab lifetime limits do not prevent XSS theft."],
      ["A JavaScript module variable persisted to IndexedDB", "Both the module and IndexedDB remain script-accessible.", "The credential stays exposed to injected JavaScript."],
    ], "a"),
    difficulty: "beginner",
    rationale: "The credential needs automatic same-site attachment but no script access, which is the security boundary provided by a Secure HttpOnly cookie.",
  }),
  defineQuestion({
    id: "q_front_05",
    categoryId: "frontend",
    subtopicId: "state_management",
    conceptId: "concept_front_state_ownership",
    sourceId: webSourceId,
    scenario: "A product page has an open accordion, authenticated user preferences shared across routes, and inventory fetched from an API that requires caching and revalidation.",
    caseType: "design_tradeoff",
    decisionCriteria: ["Place state according to ownership, lifetime, and source of truth."],
    practicalNotes: ["Do not copy server cache data into global client state unless a separate editable draft is required."],
    checkQuestion: "Which of the three values has the server as its source of truth?",
    prompt: "Which ownership split is appropriate?",
    choices: defineChoices("a", [
      ["Put all three values in one global store", "The accordion is local and inventory has server-cache semantics.", "Unrelated updates couple components and duplicate revalidation logic."],
      ["Keep accordion local, preferences global, and inventory in a server-state cache", "Each value is owned at the narrowest layer matching its lifecycle.", "Components share only durable client preferences and server data revalidates correctly."],
      ["Put all three values in component-local state", "Preferences and inventory must be shared and synchronized.", "Routes disagree and each component refetches independently."],
      ["Store all three values in the URL", "Sensitive preferences and live inventory do not belong entirely in navigation state.", "URLs become noisy and stale while ownership remains unclear."],
    ], "b"),
    difficulty: "intermediate",
    rationale: "UI disclosure is component-local, preferences are cross-route client state, and inventory remains server-owned data needing cache and revalidation.",
  }),
  defineQuestion({
    id: "q_front_06",
    categoryId: "frontend",
    subtopicId: "state_management",
    conceptId: "concept_front_async_race",
    sourceId: webSourceId,
    scenario: "A search fires for each query. The request for `cat` takes 600 ms, the later request for `caterpillar` takes 100 ms, and the UI currently renders whichever response finishes last.",
    caseType: "debugging_performance",
    decisionCriteria: ["Only the response associated with the current query may update visible results."],
    practicalNotes: ["Abort superseded work to save resources, and still guard response identity because cancellation may race completion."],
    checkQuestion: "Which request is stale when the slower response arrives?",
    prompt: "How should the UI prevent old results from replacing new ones?",
    choices: defineChoices("c", [
      ["Debounce but accept every completed response", "Debouncing reduces calls but cannot order two requests already in flight.", "The slow `cat` response can still overwrite current results."],
      ["Accept the response with the latest completion timestamp", "Completion order is the current bug and does not represent the latest user intent.", "The slow stale request can still win."],
      ["Abort the previous request and commit only the latest request ID", "Cancellation reduces wasted work and identity checking prevents stale commits.", "The `caterpillar` results remain visible."],
      ["Delay rendering until both requests finish", "Waiting increases latency and does not define which result is current.", "The UI becomes slower and can still choose incorrectly."],
    ]),
    difficulty: "intermediate",
    rationale: "Completion order differs from intent order, so the view must key commits to the latest query; aborting superseded work is an additional resource optimization.",
  }),
  defineQuestion({
    id: "q_front_07",
    categoryId: "frontend",
    subtopicId: "accessibility",
    conceptId: "concept_front_semantic_button",
    sourceId: webSourceId,
    scenario: "A clickable card action opens a dialog. It must be focusable, activate with Enter and Space, and expose a button role without custom keyboard reimplementation.",
    caseType: "basic_application",
    decisionCriteria: ["Use the native semantic element whose built-in behavior matches the action."],
    practicalNotes: ["Keep the button label descriptive and do not nest interactive elements."],
    checkQuestion: "Which element supplies keyboard activation by default?",
    prompt: "Which implementation should be used?",
    choices: defineChoices("d", [
      ["A div with only an onClick handler", "A div is not focusable or keyboard-activatable by default.", "Keyboard users cannot operate the action."],
      ["A span with role=button but no keyboard handler", "A role changes semantics but does not add native activation behavior.", "Space and Enter still fail."],
      ["An anchor without href", "An anchor without a destination does not correctly model a dialog action.", "Focus and activation behavior is inconsistent."],
      ["A native button element", "Button supplies focus, role, Enter, and Space behavior automatically.", "The action works across keyboard and assistive technology."],
    ]),
    difficulty: "beginner",
    rationale: "All required semantics and keyboard interactions are native button behavior, avoiding fragile reimplementation.",
  }),
  defineQuestion({
    id: "q_front_08",
    categoryId: "frontend",
    subtopicId: "accessibility",
    conceptId: "concept_front_form_error_association",
    sourceId: webSourceId,
    scenario: "After submit, the email field has an inline error. A screen reader must announce the invalid state and let the user navigate from the input to the exact error text.",
    caseType: "common_failure",
    decisionCriteria: ["Programmatically associate the input with persistent error text and mark its invalid state."],
    practicalNotes: ["Use an error summary for long forms, focus it after failed submit, and link entries back to fields."],
    checkQuestion: "Which attribute points from the input to the error element ID?",
    prompt: "Which markup pattern meets the requirement?",
    choices: defineChoices("a", [
      ["Set aria-invalid=true and aria-describedby to the error element ID", "The attributes expose invalidity and attach the exact explanatory text.", "Assistive technology can announce and revisit the error."],
      ["Color the input border red", "Color alone creates no programmatic error relationship.", "Screen-reader and color-blind users may miss the error."],
      ["Put the error only in a toast", "A transient toast is not reliably connected to the field.", "Users cannot navigate the relationship later."],
      ["Use placeholder text as the error", "Placeholder content is not a durable label or error association.", "The message disappears during input and may not be announced."],
    ]),
    difficulty: "intermediate",
    rationale: "The requirement is a programmatic field-to-error link plus invalid state, supplied by aria-describedby and aria-invalid when native validation text is not used.",
  }),
  defineQuestion({
    id: "q_front_09",
    categoryId: "frontend",
    subtopicId: "typescript",
    conceptId: "concept_front_exhaustive_union",
    sourceId: tsSourceId,
    scenario: "A reducer handles every PaymentState variant. Adding a new variant must cause a compile error until the rendering branch is implemented.",
    artifacts: [{
      kind: "code",
      title: "Payment state",
      language: "typescript",
      content: "type PaymentState =\n  | { kind: \"idle\" }\n  | { kind: \"processing\"; startedAt: number }\n  | { kind: \"failed\"; message: string };\n\nfunction assertNever(value: never): never {\n  throw new Error(`Unhandled state: ${JSON.stringify(value)}`);\n}\n\nfunction label(state: PaymentState): string {\n  switch (state.kind) {\n    case \"idle\": return \"Ready\";\n    case \"processing\": return \"Processing\";\n    case \"failed\": return state.message;\n    default: return assertNever(state);\n  }\n}",
    }],
    caseType: "maintainability_safety",
    decisionCriteria: ["Make exhaustiveness a compile-time property of the discriminated union."],
    practicalNotes: ["Do not add a broad default return that hides newly added variants."],
    checkQuestion: "Why is state typed never in a fully exhaustive default branch?",
    prompt: "Which pattern enforces the requirement?",
    choices: defineChoices("b", [
      ["Return an empty string from default", "A permissive default accepts future variants silently.", "New states render blank without a compiler signal."],
      ["Pass the default value to an assertNever function", "A missing case leaves a non-never value and fails type checking.", "Every new variant requires an explicit rendering decision."],
      ["Cast state.kind to string", "Widening removes the finite discriminant information.", "Typos and missing variants become harder to detect."],
      ["Use optional chaining on every property", "Optional access does not prove the union is exhaustive.", "Unhandled variants still reach runtime."],
    ]),
    difficulty: "advanced",
    rationale: "A never-accepting default converts discriminated-union exhaustiveness into a compiler check whenever a new PaymentState variant is added.",
  }),
  defineQuestion({
    id: "q_front_10",
    categoryId: "frontend",
    subtopicId: "browsers",
    conceptId: "concept_front_cross_platform_tokens",
    sourceId: webSourceId,
    scenario: "Two brands ship Web, iOS, and Android clients. Each client supports light and dark mode, while semantic roles such as surface-danger must stay consistent despite platform-specific output formats.",
    artifacts: [{
      kind: "schema",
      title: "Semantic token source",
      language: "json",
      content: "{\"color\":{\"surface\":{\"danger\":{\"$type\":\"color\",\"$value\":\"{brand.danger.surface}\"}}}}",
    }],
    caseType: "design_tradeoff",
    decisionCriteria: ["Keep semantic intent in one source while allowing brand, theme, and platform transformations."],
    practicalNotes: ["Validate contrast after every brand/theme mapping; token consistency does not guarantee accessibility."],
    checkQuestion: "Which layer changes between brands while component code keeps semantic names?",
    prompt: "Which token architecture best controls drift across all clients?",
    choices: defineChoices("c", [
      ["Copy raw hex values into every component repository", "Independent copies lose semantic intent and drift across releases.", "Brand or dark-mode changes require risky multi-client edits."],
      ["Use one fixed palette for every brand and theme", "The requirement explicitly includes multiple brands and light/dark themes.", "Products cannot express required variants."],
      ["Store semantic tokens centrally and transform aliases per brand, theme, and platform", "Semantic roles stay stable while mappings generate CSS, Swift, and Android resources.", "All clients receive reviewable, synchronized outputs."],
      ["Let each client team maintain its own platform token file from the design spec", "Separate files are usable but lack one versioned source for synchronized brand and theme changes.", "Web and mobile mappings drift between release cycles."],
    ]),
    difficulty: "advanced",
    rationale: "A central semantic layer captures cross-client intent, while alias transforms provide the explicitly required brand, theme, and platform variations.",
  }),
];
