import type { ReviewedQuestion } from "@/lib/quiz/content/types";
import { defineChoices, defineQuestion } from "@/lib/quiz/content/questions/helpers";

const sourceId = "source_sre_operations";

export const infrastructureQuestions: ReviewedQuestion[] = [
  defineQuestion({
    id: "q_infra_01",
    categoryId: "infrastructure",
    subtopicId: "cloud",
    conceptId: "concept_infra_managed_service",
    sourceId,
    scenario: "A four-person team needs PostgreSQL with automated backups, point-in-time recovery, patching, and on-call coverage. The database is standard and provider lock-in is acceptable.",
    caseType: "basic_application",
    decisionCriteria: ["Minimize undifferentiated operations while meeting backup and recovery needs."],
    practicalNotes: ["Verify restore procedures and export paths; managed does not remove ownership of recovery testing."],
    checkQuestion: "Which listed duties would the team otherwise have to staff continuously?",
    prompt: "Which deployment choice best fits the constraints?",
    choices: defineChoices("d", [
      ["Self-host PostgreSQL on one VM", "One VM leaves backups, failover, patching, and paging to the small team.", "Operational load and single-host risk remain high."],
      ["Build a custom distributed database", "The workload needs standard PostgreSQL rather than a novel storage engine.", "Delivery is delayed by unnecessary engineering."],
      ["Run PostgreSQL in developer laptops", "Laptops cannot provide production durability or continuous access.", "Data and availability are lost with local machines."],
      ["Use a managed PostgreSQL service with tested recovery", "The provider supplies routine operations that the team cannot staff efficiently.", "The team can focus on schema and restore verification."],
    ]),
    difficulty: "beginner",
    rationale: "The tiny team, standard workload, accepted lock-in, and explicit operational requirements make managed PostgreSQL the constrained choice.",
  }),
  defineQuestion({
    id: "q_infra_02",
    categoryId: "infrastructure",
    subtopicId: "cloud",
    conceptId: "concept_infra_rto_rpo",
    sourceId,
    scenario: "Checkout requires an RTO of 10 minutes after a regional outage and an RPO under one minute. Restoring a daily backup in another region takes four hours.",
    caseType: "common_failure",
    decisionCriteria: ["Provide cross-region recovery within both the ten-minute time and one-minute data-loss limits."],
    practicalNotes: ["Run failover drills and measure replication lag; diagrams do not prove RTO or RPO."],
    checkQuestion: "Why does a daily backup fail both objectives?",
    prompt: "Which architecture can meet the stated recovery objectives?",
    choices: defineChoices("a", [
      ["Maintain a warm secondary region with continuous replication and automated failover", "Continuous replication constrains data loss and pre-provisioned capacity shortens restoration.", "A tested failover can recover within minutes with sub-minute lag."],
      ["Keep the single region and restore nightly backups", "Nightly copies can lose nearly a day and take four hours to restore.", "Both RPO and RTO are violated."],
      ["Add more instances only in the primary region", "In-region redundancy does not survive a regional outage.", "All instances fail together."],
      ["Archive logs monthly in cold storage", "Monthly archival is for retention, not rapid operational recovery.", "Recovery time and data loss are far outside targets."],
    ]),
    difficulty: "advanced",
    rationale: "Only continuously replicated, ready cross-region capacity can simultaneously satisfy sub-minute data loss and ten-minute service restoration.",
  }),
  defineQuestion({
    id: "q_infra_03",
    categoryId: "infrastructure",
    subtopicId: "containers",
    conceptId: "concept_infra_reproducible_image",
    sourceId,
    scenario: "A Node image rebuild downloads floating dependency versions and copies the entire repository before install, so unrelated README edits invalidate a 1 GB dependency layer.",
    artifacts: [{
      kind: "config",
      title: "Current Dockerfile",
      language: "dockerfile",
      content: "FROM node:latest\nWORKDIR /app\nCOPY . .\nRUN npm install\nRUN npm run build",
    }],
    caseType: "design_tradeoff",
    decisionCriteria: ["Make dependencies reproducible and keep their cached layer stable when only application source changes."],
    practicalNotes: ["Pin the base image digest and use a .dockerignore to exclude secrets and irrelevant build context."],
    checkQuestion: "Which files should be copied before the dependency install layer?",
    prompt: "Which Dockerfile strategy fixes both problems?",
    choices: defineChoices("b", [
      ["Keep COPY first and add --no-cache", "Disabling cache increases rebuild work and does not pin dependencies.", "Every change repeats the slow non-reproducible install."],
      ["Pin the base, copy lockfiles first, run a frozen install, then copy source", "Lockfiles make resolution deterministic and layer order preserves the dependency cache.", "Source-only edits rebuild small later layers."],
      ["Delete the lockfile before every build", "Without a lockfile, transitive versions float.", "Identical source can produce different images."],
      ["Mount the host node_modules into production", "Host dependencies differ by platform and bypass image reproducibility.", "Deployments depend on the build machine."],
    ]),
    difficulty: "intermediate",
    rationale: "The two observed causes are floating inputs and premature source copying; pinned inputs plus lockfile-first layers address each directly.",
  }),
  defineQuestion({
    id: "q_infra_04",
    categoryId: "infrastructure",
    subtopicId: "containers",
    conceptId: "concept_infra_oom_limit",
    sourceId,
    scenario: "A container restarts with exit code 137. Metrics show memory climbs to its 512 MiB cgroup limit while node memory remains available; CPU and liveness latency are normal.",
    caseType: "debugging_performance",
    decisionCriteria: ["Diagnose the container-level memory termination from the limit and usage evidence."],
    practicalNotes: ["Capture heap profiles and bound caches before raising a limit; increasing capacity can hide a leak."],
    checkQuestion: "What does exit 137 commonly indicate in this cgroup context?",
    prompt: "What should the team investigate first?",
    choices: defineChoices("c", [
      ["A DNS timeout", "DNS failures do not explain memory reaching the cgroup limit or exit 137.", "Networking changes leave restarts unchanged."],
      ["A CPU throttling loop", "CPU and liveness latency are normal.", "CPU limits are adjusted without evidence."],
      ["An OOM kill caused by process growth against the memory limit", "The measured climb to the cgroup ceiling matches kernel termination.", "Heap profiling can identify a leak, unbounded cache, or undersized limit."],
      ["A failed readiness probe", "Readiness removes traffic but does not normally kill the container.", "Probe tuning obscures the actual memory failure."],
    ]),
    difficulty: "intermediate",
    rationale: "Exit 137 plus usage at the cgroup ceiling, despite free node memory, specifically points to a container memory-limit OOM kill.",
  }),
  defineQuestion({
    id: "q_infra_05",
    categoryId: "infrastructure",
    subtopicId: "ci_cd",
    conceptId: "concept_infra_artifact_promotion",
    sourceId,
    scenario: "Staging and production currently rebuild the same commit separately. A registry mirror changed between builds, so production received bytes that never passed staging tests.",
    caseType: "maintainability_safety",
    decisionCriteria: ["Promote the exact tested immutable artifact rather than reproducing it."],
    practicalNotes: ["Sign the artifact, store an SBOM, and deploy by digest rather than a mutable tag."],
    checkQuestion: "Which identifier proves production uses the bytes tested in staging?",
    prompt: "How should the pipeline prevent this mismatch?",
    choices: defineChoices("d", [
      ["Rebuild faster in production", "Speed does not make two builds byte-identical.", "Untested bytes can still be deployed."],
      ["Use the same mutable latest tag", "A tag can point to different content over time.", "Promotion does not identify the tested image."],
      ["Run fewer staging tests", "Reducing tests cannot establish artifact identity.", "Both quality and provenance weaken."],
      ["Build once, test it, and promote the same digest", "An immutable digest binds each environment to identical bytes.", "Production receives the artifact that passed tests."],
    ]),
    difficulty: "intermediate",
    rationale: "The incident came from rebuilding, so one build promoted by immutable digest is the direct control connecting test evidence to deployed bytes.",
  }),
  defineQuestion({
    id: "q_infra_06",
    categoryId: "infrastructure",
    subtopicId: "ci_cd",
    conceptId: "concept_infra_expand_contract",
    sourceId,
    scenario: "A zero-downtime deployment will rename users.full_name while old and new application versions run together for 30 minutes. The table has 80 million rows.",
    caseType: "basic_application",
    decisionCriteria: ["Keep both versions compatible and avoid one long blocking rewrite."],
    practicalNotes: ["Define a reconciliation window and metrics before removing the old read/write path."],
    checkQuestion: "At what point is it safe to drop the old column?",
    prompt: "Which migration sequence is safest?",
    choices: defineChoices("a", [
      ["Add the new column, dual-write, backfill in batches, switch reads, then remove the old column later", "Expand-contract keeps both versions functional while a bounded backfill progresses.", "Rollback remains possible until the final delayed cleanup."],
      ["Rename and drop the old column before deploying code", "The old application still reads the original column.", "Requests fail during the mixed-version window."],
      ["Lock the table and rewrite all rows in one transaction", "An 80-million-row blocking rewrite violates zero downtime.", "Writes stall and rollback is risky."],
      ["Deploy new code that assumes the new column exists, then migrate", "New instances can query a missing column.", "The rollout fails before the schema catches up."],
    ]),
    difficulty: "advanced",
    rationale: "Mixed application versions and a huge table require expand-contract compatibility plus batched backfill, with destructive cleanup only after old readers are gone.",
  }),
  defineQuestion({
    id: "q_infra_07",
    categoryId: "infrastructure",
    subtopicId: "observability",
    conceptId: "concept_infra_signal_selection",
    sourceId,
    scenario: "A checkout request is slow only when it calls inventory and payment across six services. The team needs to locate which hop consumed the latency for one request.",
    caseType: "common_failure",
    decisionCriteria: ["Correlate timing across service boundaries for an individual request."],
    practicalNotes: ["Propagate trace context at every hop and attach low-cardinality service metadata."],
    checkQuestion: "Which signal shows a waterfall of child operations for one request?",
    prompt: "Which telemetry is the primary diagnostic signal?",
    choices: defineChoices("b", [
      ["A daily CPU average", "A fleet average cannot reveal one request's service path.", "The slow hop remains hidden."],
      ["A distributed trace with spans across all six services", "Trace spans preserve causal path and per-hop duration.", "The team can identify the latency-contributing dependency."],
      ["An unstructured log line from checkout only", "One local log lacks downstream timing and correlation.", "Engineers manually guess at remote behavior."],
      ["A count of successful deployments", "Deployment count does not show request latency.", "No execution evidence is collected."],
    ]),
    difficulty: "beginner",
    rationale: "The question asks for one request's latency across multiple hops, which is the causal timing model supplied by distributed traces.",
  }),
  defineQuestion({
    id: "q_infra_08",
    categoryId: "infrastructure",
    subtopicId: "observability",
    conceptId: "concept_infra_metric_cardinality",
    sourceId,
    scenario: "A counter labels every sample with user_id and request_id. The metrics backend now stores 30 million active series and query latency has collapsed.",
    caseType: "design_tradeoff",
    decisionCriteria: ["Keep metric dimensions bounded while preserving per-request detail in a suitable signal."],
    practicalNotes: ["Allowlist label values and review expected cardinality before instrumenting production."],
    checkQuestion: "Why do user_id and request_id create a new series for nearly every event?",
    prompt: "What is the correct remediation?",
    choices: defineChoices("c", [
      ["Increase scrape frequency", "More samples amplify ingestion without reducing series count.", "Storage and query pressure worsen."],
      ["Hash request_id into another label", "A near-unique hash remains near-unique.", "Cardinality stays unbounded."],
      ["Remove unique IDs from metrics; keep bounded labels and put IDs in logs or traces", "Metrics aggregate dimensions while logs and traces support individual-event lookup.", "Series count returns to a manageable bound without losing correlation data."],
      ["Add user email as another label", "Email is also high-cardinality and sensitive.", "Cost and privacy risk both increase."],
    ]),
    difficulty: "intermediate",
    rationale: "The backend is failing from unbounded metric dimensions, so unique identifiers must move to event-oriented logs/traces while metrics retain bounded labels.",
  }),
  defineQuestion({
    id: "q_infra_09",
    categoryId: "infrastructure",
    subtopicId: "cloud",
    conceptId: "concept_infra_reverse_proxy",
    sourceId,
    scenario: "Public HTTPS requests for api.example.com must terminate TLS at one edge, route /billing and /catalog to separate private upstream pools, and load balance healthy instances.",
    artifacts: [{
      kind: "config",
      title: "Required edge behavior",
      language: "text",
      content: "TLS: api.example.com\n/billing -> billing upstreams\n/catalog -> catalog upstreams\nhealth checks: required",
    }],
    caseType: "debugging_performance",
    decisionCriteria: ["Choose the intermediary that represents servers to clients and routes inbound traffic."],
    practicalNotes: ["Re-encrypt to upstreams when the internal threat model requires end-to-end transport protection."],
    checkQuestion: "Is this proxy acting on behalf of outbound clients or inbound servers?",
    prompt: "Which component provides the required edge behavior?",
    choices: defineChoices("d", [
      ["A recursive DNS resolver", "DNS maps names to addresses but does not terminate TLS or route by path.", "Application routing and health balancing remain absent."],
      ["A NAT gateway", "NAT translates network addresses and does not inspect HTTPS paths after TLS termination.", "Requests cannot be split by application route."],
      ["A forward proxy for employee outbound browsing", "A forward proxy represents clients reaching external servers, the opposite traffic direction.", "It does not expose and balance the private application pools."],
      ["A reverse proxy or application load balancer", "A reverse proxy represents upstream servers, terminates TLS, routes paths, and balances healthy targets.", "One controlled edge satisfies all inbound routing requirements."],
    ]),
    difficulty: "beginner",
    rationale: "The component fronts private servers for inbound clients and needs TLS termination, path routing, and load balancing—the defining reverse-proxy role.",
  }),
  defineQuestion({
    id: "q_infra_10",
    categoryId: "infrastructure",
    subtopicId: "observability",
    conceptId: "concept_infra_slo_burn_alert",
    sourceId,
    scenario: "CPU crosses 80% during healthy batch work and pages weekly, but users care about 99.9% monthly request success. A recent low-CPU dependency outage exhausted half the error budget unnoticed.",
    caseType: "maintainability_safety",
    decisionCriteria: ["Page on sustained user-impact risk relative to the service error budget."],
    practicalNotes: ["Use fast and slow burn windows so severe incidents page quickly and gradual exhaustion still surfaces."],
    checkQuestion: "Which event consumed error budget despite low CPU?",
    prompt: "What should replace the static CPU page?",
    choices: defineChoices("a", [
      ["Multi-window error-budget burn alerts on the request-success SLO", "Burn rate tracks how quickly actual failures consume the user-facing budget.", "Healthy batch CPU stops paging while dependency errors trigger action."],
      ["A lower 60% CPU threshold", "A lower resource threshold creates more unrelated alerts.", "Dependency failures can still go unseen."],
      ["Page on every individual 5xx", "Single failures create noise and ignore the SLO's tolerated budget.", "Responders become desensitized to alerts."],
      ["Disable paging during batch hours", "A real user-impacting incident can occur during the same window.", "Operational silence replaces signal quality."],
    ]),
    difficulty: "advanced",
    rationale: "The current symptom alert is both noisy and blind; error-budget burn directly represents the stated 99.9% user outcome across fast and slow failure rates.",
  }),
];
