import type { ReviewedQuestion } from "@/lib/quiz/content/types";
import { defineChoices, defineQuestion } from "@/lib/quiz/content/questions/helpers";

const sourceId = "source_owasp_guidance";

export const securityQuestions: ReviewedQuestion[] = [
  defineQuestion({
    id: "q_sec_01",
    categoryId: "security",
    subtopicId: "authorization",
    conceptId: "concept_sec_object_authorization",
    sourceId,
    scenario: "GET /api/orders/:id authenticates the caller, then loads any order by numeric ID. A normal user changed 481 to 482 and viewed another customer's order.",
    caseType: "common_failure",
    decisionCriteria: ["Authorize every requested object against the caller or tenant, independent of ID predictability."],
    practicalNotes: ["Centralize ownership scoping in the data-access boundary and test cross-tenant IDs."],
    checkQuestion: "Why does authentication alone not authorize order 482?",
    prompt: "Which change prevents this IDOR vulnerability?",
    choices: defineChoices("a", [
      ["Query the order by both id and the authorized customer or tenant ID", "The object lookup itself enforces ownership for every request.", "Another customer's record is not returned even when its ID is known."],
      ["Replace numeric IDs with UUIDs", "Unpredictability reduces guessing but does not enforce authorization.", "A leaked UUID still exposes the order."],
      ["Hide the order ID in JavaScript", "Client-side concealment is not a server security boundary.", "Attackers can construct requests directly."],
      ["Check only that the caller has a valid session", "A session proves identity, not rights to a specific object.", "Any authenticated user can still enumerate orders."],
    ]),
    difficulty: "intermediate",
    rationale: "The failure is missing object-level authorization, so binding the order query to the authenticated owner or tenant prevents cross-customer access regardless of identifier format.",
  }),
  defineQuestion({
    id: "q_sec_02",
    categoryId: "security",
    subtopicId: "authorization",
    conceptId: "concept_sec_role_and_ownership",
    sourceId,
    scenario: "Editors may modify only documents in their assigned workspace; admins may modify any workspace. The current check allows every user with role=editor to edit any document.",
    caseType: "design_tradeoff",
    decisionCriteria: ["Combine coarse role capability with resource-scope authorization."],
    practicalNotes: ["Evaluate the rule server-side after loading trusted workspace membership."],
    checkQuestion: "What additional fact must be checked for an editor?",
    prompt: "Which authorization rule is correct?",
    choices: defineChoices("d", [
      ["Allow anyone who can see the edit button", "UI visibility is client-controlled and not an authorization decision.", "Direct API calls bypass the check."],
      ["Allow every authenticated user", "Authentication does not grant document mutation rights.", "Viewers can alter protected documents."],
      ["Allow admins, or editors whose assigned workspace owns the document", "The rule checks both permitted action and resource scope.", "Editors stay confined while admins retain global access."],
      ["Allow every editor and log cross-workspace changes", "Audit logging records abuse but does not prevent it.", "Unauthorized edits still occur."],
    ], "c"),
    difficulty: "intermediate",
    rationale: "Role=editor authorizes an action class but the stated policy also requires workspace ownership, so both conditions must be evaluated.",
  }),
  defineQuestion({
    id: "q_sec_03",
    categoryId: "security",
    subtopicId: "vulnerabilities",
    conceptId: "concept_sec_parameterized_sql",
    sourceId,
    scenario: "A login lookup concatenates the submitted email into SQL. Inputs may contain quotes and SQL metacharacters, and the query structure must never change with input.",
    artifacts: [{
      kind: "sql",
      title: "Unsafe query construction",
      language: "sql",
      content: "SELECT id, password_hash FROM users WHERE email = '" + "${email}" + "';",
    }],
    caseType: "basic_application",
    decisionCriteria: ["Keep user data separate from the parsed SQL statement."],
    practicalNotes: ["Use the driver parameter API; hand-written escaping is database-specific and easy to omit."],
    checkQuestion: "Who should encode the submitted value for the database protocol?",
    prompt: "Which implementation prevents SQL injection?",
    choices: defineChoices("b", [
      ["Remove single quotes with a string replacement", "An incomplete blacklist misses alternate encodings and other syntax.", "Attackers can still alter the query."],
      ["Use SELECT ... WHERE email = ? with a bound parameter", "The driver transmits the value separately from the SQL structure.", "Metacharacters remain data and cannot add clauses."],
      ["Base64-encode the full query", "Encoding is not parsing or parameterization.", "The server must decode and execute the same unsafe query."],
      ["Reject emails longer than 100 characters", "Length bounds do not prevent short injection payloads.", "The statement remains structurally controllable."],
    ]),
    difficulty: "beginner",
    rationale: "The explicit requirement is invariant query structure, achieved by a prepared parameter rather than attempting to sanitize SQL syntax manually.",
  }),
  defineQuestion({
    id: "q_sec_04",
    categoryId: "security",
    subtopicId: "vulnerabilities",
    conceptId: "concept_sec_contextual_encoding",
    sourceId,
    scenario: "A comment containing `<img src=x onerror=alert(1)>` is stored legitimately, then inserted into a page's HTML body. Users must see the literal text, not execute markup.",
    caseType: "basic_application",
    decisionCriteria: ["Encode untrusted text for the exact HTML output context at render time."],
    practicalNotes: ["If rich HTML is required instead, use an allowlist sanitizer designed for HTML and still avoid dangerous URL/script contexts."],
    checkQuestion: "Why is storing the original comment compatible with safe rendering?",
    prompt: "What is the correct defense at this boundary?",
    choices: defineChoices("c", [
      ["Strip the word alert during input", "A keyword blacklist misses countless executable payloads.", "Other event handlers or encodings execute."],
      ["Trust stored content because it passed through the database", "Storage does not make untrusted data safe for HTML.", "Persistent XSS reaches every viewer."],
      ["Escape the complete page after rendering", "Whole-page escaping destroys intended markup and mixes contexts.", "The application either breaks or reintroduces unsafe exceptions."],
      ["HTML-encode the comment when inserting it into the text context", "Contextual encoding converts markup delimiters into displayable text.", "The browser renders the payload literally rather than parsing an element."],
    ], "d"),
    difficulty: "intermediate",
    rationale: "The application needs plain text in an HTML body context, so output encoding at that sink preserves the value while preventing browser interpretation.",
  }),
  defineQuestion({
    id: "q_sec_05",
    categoryId: "security",
    subtopicId: "secret_handling",
    conceptId: "concept_sec_external_secret",
    sourceId,
    scenario: "A production database password is committed in app.config.ts and copied into container images. Different environments need separate credentials and repository readers must not obtain them.",
    caseType: "debugging_performance",
    decisionCriteria: ["Remove secret material from source and image layers; inject scoped values at runtime."],
    practicalNotes: ["Assume the committed credential is compromised: rotate it and scrub exposure history where appropriate."],
    checkQuestion: "Why is deleting the current line insufficient after it was committed?",
    prompt: "Which remediation establishes the correct secret boundary?",
    choices: defineChoices("d", [
      ["Obfuscate the password with Base64 in the same file", "Base64 is reversible encoding and the bytes remain in the repository.", "Readers recover the credential immediately."],
      ["Pass the same password as a Docker build argument", "Build arguments can remain in image history and still couple one credential to builds.", "Repository exposure changes form, but image readers and build logs may recover the secret."],
      ["Rotate it, store replacements in a secret manager, and inject them at runtime", "Runtime retrieval keeps environment-scoped credentials out of source and build layers.", "Access can be audited, limited, and rotated independently."],
      ["Encrypt the password in source with a decryption key bundled in the application", "A co-located key lets anyone with the image recover the credential.", "The repository text is opaque, but the runtime artifact still contains everything needed to decrypt it."],
    ], "c"),
    difficulty: "beginner",
    rationale: "The secret crossed both repository and image boundaries, so remediation requires rotation plus a runtime secret manager rather than concealment inside source.",
  }),
  defineQuestion({
    id: "q_sec_06",
    categoryId: "security",
    subtopicId: "secret_handling",
    conceptId: "concept_sec_zero_downtime_rotation",
    sourceId,
    scenario: "A payment API credential used by 30 instances expires Friday. The provider supports two active keys, and requests must continue during a rolling deployment.",
    caseType: "maintainability_safety",
    decisionCriteria: ["Create an overlap window so old and new instances authenticate throughout rollout."],
    practicalNotes: ["Monitor new-key use, retain a tested rollback window, then revoke the old key promptly."],
    checkQuestion: "When is it safe to revoke the old credential?",
    prompt: "Which rotation sequence avoids an outage?",
    choices: defineChoices("b", [
      ["Revoke the old key, then create a replacement", "All running instances lose authentication before receiving the new value.", "Payment requests fail immediately."],
      ["Create a second key, deploy and verify it everywhere, then revoke the old key", "Dual validity covers the rolling mixed-version period.", "Traffic continues while adoption is measured."],
      ["Keep both keys active forever", "Permanent overlap expands the credential attack surface.", "A compromised old key remains useful."],
      ["Email the new key to every developer", "Manual distribution is unaudited and unrelated to runtime rollout.", "Secret exposure grows and instances may remain stale."],
    ]),
    difficulty: "intermediate",
    rationale: "Provider support for two keys exists specifically to overlap a rolling rollout; verification must precede revocation to avoid invalidating old instances.",
  }),
  defineQuestion({
    id: "q_sec_07",
    categoryId: "security",
    subtopicId: "supply_chain",
    conceptId: "concept_sec_dependency_provenance",
    sourceId,
    scenario: "CI resolves floating dependency ranges and downloads unsigned packages from whichever mirror responds. Releases must be reproducible and tied to reviewed package versions and provenance.",
    caseType: "maintainability_safety",
    decisionCriteria: ["Pin the resolved dependency graph and verify artifact origin/integrity in CI."],
    practicalNotes: ["Review lockfile changes like source changes and retain an SBOM for incident lookup."],
    checkQuestion: "Which file records the exact transitive package graph?",
    prompt: "Which control set best meets the release requirement?",
    choices: defineChoices("a", [
      ["Delete the lockfile on every build", "Fresh resolution permits transitive versions to change without review.", "Identical commits produce different artifacts."],
      ["Trust packages with many downloads", "Popularity is not provenance or integrity verification.", "A compromised popular package still enters the build."],
      ["Use only semantic version ranges and HTTP caching", "Ranges intentionally allow new bytes, and cache origin is not trust.", "Unreviewed updates reach releases."],
      ["Commit a lockfile, use frozen installs, pin critical versions, and verify signatures or checksums", "Exact resolution plus provenance checks binds reviewed names and versions to downloaded bytes.", "Rebuilds are deterministic and tampering is detected."],
    ], "d"),
    difficulty: "advanced",
    rationale: "The stated threats are version drift and untrusted package origin, so both a frozen lockfile and integrity/provenance verification are required.",
  }),
  defineQuestion({
    id: "q_sec_08",
    categoryId: "security",
    subtopicId: "supply_chain",
    conceptId: "concept_sec_compromised_package_response",
    sourceId,
    scenario: "A dependency maintainer reports that version 4.2.1 exfiltrates environment variables during install. CI used that version yesterday to build production, and the build had registry and deployment credentials.",
    caseType: "debugging_performance",
    decisionCriteria: ["Contain credential abuse, identify affected artifacts, eradicate the package, and recover from trusted inputs."],
    practicalNotes: ["Preserve logs and package artifacts for forensics before normal retention removes them."],
    checkQuestion: "Which credentials must be treated as exposed even without a confirmed outbound log?",
    prompt: "What is the first complete incident response?",
    choices: defineChoices("d", [
      ["Stop affected pipelines, rotate exposed credentials, inventory builds, remove the version, and rebuild clean artifacts", "The sequence contains ongoing execution and assumes secrets available to install code were exposed.", "Compromised access is revoked and known-good releases can replace affected ones."],
      ["Only upgrade the dependency next month", "Delayed eradication leaves credentials and deployed artifacts unaddressed.", "The attacker may continue using stolen access."],
      ["Quarantine current artifacts but keep using the same CI credentials during investigation", "Quarantine limits deployment but leaves credentials exposed to malicious install code usable.", "The attacker may retain registry or deployment access."],
      ["Remove version 4.2.1 from the lockfile without rotating credentials or rebuilding releases", "Dependency removal protects later installs but does not revoke stolen secrets or replace affected bytes.", "Existing access and deployed artifacts remain compromised."],
    ], "a"),
    difficulty: "advanced",
    rationale: "Malicious install code had direct access to deployment secrets, so response must combine containment, credential rotation, scoping, eradication, and trusted rebuilds.",
  }),
  defineQuestion({
    id: "q_sec_09",
    categoryId: "security",
    subtopicId: "vulnerabilities",
    conceptId: "concept_sec_csrf_cookie_session",
    sourceId,
    scenario: "A browser automatically sends the session cookie to POST /transfer. An attacker can cause a logged-in browser to submit a cross-site form, but cannot read same-origin responses.",
    caseType: "common_failure",
    decisionCriteria: ["Require proof that a state-changing request originated from the trusted site, not merely possession of an automatic cookie."],
    practicalNotes: ["SameSite helps but keep an explicit token for flows that require cross-site cookie behavior."],
    checkQuestion: "Why can an attacker send the cookie without learning its value?",
    prompt: "Which defense should the transfer endpoint enforce?",
    choices: defineChoices("c", [
      ["Check that the session cookie exists", "The browser attaches the cookie to the forged request.", "The attack still appears authenticated."],
      ["Hide the transfer form URL", "Endpoint secrecy is not an origin proof.", "Attackers can discover or guess the route."],
      ["Return JSON instead of HTML", "Response format does not prevent a state-changing request from being sent.", "The transfer still executes."],
      ["Validate a per-session CSRF token and Origin, with an appropriate SameSite cookie", "The attacker cannot read the trusted token and origin checks detect cross-site submission.", "Forged state changes are rejected before execution."],
    ], "d"),
    difficulty: "intermediate",
    rationale: "Automatic cookie attachment creates CSRF, so the endpoint needs a non-automatic same-origin proof such as a token, reinforced by Origin and SameSite controls.",
  }),
  defineQuestion({
    id: "q_sec_10",
    categoryId: "security",
    subtopicId: "authorization",
    conceptId: "concept_sec_service_least_privilege",
    sourceId,
    scenario: "A report service only SELECTs analytics views but uses the same database credential as migrations, which can DROP tables and access customer secrets.",
    caseType: "design_tradeoff",
    decisionCriteria: ["Grant only the operations and data scope required by the report runtime."],
    practicalNotes: ["Separate runtime, migration, and break-glass credentials and alert on denied privilege escalation attempts."],
    checkQuestion: "Which privileges does the running report process actually need?",
    prompt: "How should the credential be redesigned?",
    choices: defineChoices("b", [
      ["Keep the admin credential and enforce an application query allowlist", "An application allowlist is bypassable after service compromise and leaves database privileges unchanged.", "Injected or unintended code still reaches destructive permissions."],
      ["Issue a report-specific read-only credential limited to required views", "The identity can perform its SELECT workload but not migrations or secret-table reads.", "Compromise impact is constrained to approved report data."],
      ["Share one read-only credential across every service and schema", "Read-only removes writes but grants the report service access to unrelated customer data.", "A report compromise can read far beyond the required analytics views."],
      ["Keep the admin credential but restrict database network access to the report service", "A network allowlist limits callers, not what a compromised allowed caller can execute.", "The report process still has DROP and secret-table privileges."],
    ]),
    difficulty: "beginner",
    rationale: "The runtime performs only SELECTs on analytics views, so a distinct identity scoped to exactly those operations enforces least privilege.",
  }),
];
