import type { ReviewedQuestion } from "@/lib/quiz/content/types";
import { defineChoices, defineQuestion } from "@/lib/quiz/content/questions/helpers";

const sourceId = "source_distributed_systems";

export const softwareDesignQuestions: ReviewedQuestion[] = [
  defineQuestion({
    id: "q_design_01",
    categoryId: "software_design",
    subtopicId: "distributed_systems",
    conceptId: "concept_design_inventory_consistency",
    sourceId,
    scenario: "A flash sale has one physical item left. Payment authorization may proceed only for one buyer; showing stale browse counts for two seconds is acceptable, but overselling is not.",
    caseType: "basic_application",
    decisionCriteria: ["Serialize the final stock reservation while allowing weaker consistency for browse-only displays."],
    practicalNotes: ["Keep the reservation transaction short and expire abandoned reservations."],
    checkQuestion: "Which operation requires the stronger consistency guarantee?",
    prompt: "Which design meets the business rule?",
    choices: defineChoices("c", [
      ["Accept both orders and reconcile later", "Reconciliation permits the explicitly forbidden oversell.", "One paid customer cannot receive the item."],
      ["Use the stale browse cache as the reservation authority", "A cache value can show one unit to multiple buyers.", "Concurrent checkouts both proceed."],
      ["Perform an atomic conditional reservation in the inventory authority", "A compare-and-update or locked transaction lets only one zero-to-one transition succeed.", "Browse remains fast while checkout cannot oversell."],
      ["Make every catalog read globally serializable", "Browse tolerates staleness and does not need checkout-level coordination.", "Latency and availability costs rise without protecting more reservations."],
    ]),
    difficulty: "advanced",
    rationale: "Only the final reservation has a no-oversell invariant, so it must be atomic at the inventory authority while browse views may remain eventually consistent.",
  }),
  defineQuestion({
    id: "q_design_02",
    categoryId: "software_design",
    subtopicId: "distributed_systems",
    conceptId: "concept_design_event_idempotency",
    sourceId,
    scenario: "An at-least-once order_created event can be delivered again after consumer restart. The fulfillment service must create exactly one shipment per order.",
    caseType: "common_failure",
    decisionCriteria: ["Make duplicate delivery converge on one durable shipment effect."],
    practicalNotes: ["Use the event or order ID as a unique business key in the same transaction as shipment creation."],
    checkQuestion: "Which persisted uniqueness rule turns replay into a no-op?",
    prompt: "How should the consumer be designed?",
    choices: defineChoices("b", [
      ["Acknowledge before creating the shipment", "A crash after acknowledgement loses the shipment permanently.", "The order may never be fulfilled."],
      ["Insert shipment with a unique order_id and treat conflict as already processed", "The database rejects a second effect for the same business key.", "Redelivery safely returns the existing shipment."],
      ["Remember recent IDs only in memory", "Restart erases the deduplication state in the stated failure case.", "A second shipment is created."],
      ["Ask the broker for exactly-once delivery", "Broker semantics cannot make an external database effect atomic automatically.", "The acknowledge/write failure window remains."],
    ]),
    difficulty: "intermediate",
    rationale: "At-least-once delivery is an input constraint, so durable uniqueness on order_id must make the fulfillment effect idempotent across restarts.",
  }),
  defineQuestion({
    id: "q_design_03",
    categoryId: "software_design",
    subtopicId: "distributed_systems",
    conceptId: "concept_design_circuit_breaker",
    sourceId,
    scenario: "A recommendation dependency is timing out for 20 seconds. Checkout does not require recommendations, but 200 request threads are waiting and retries are amplifying load.",
    caseType: "design_tradeoff",
    decisionCriteria: ["Protect checkout capacity, bound waiting, and recover the optional feature cautiously."],
    practicalNotes: ["Use jittered retry budgets and probe half-open recovery instead of reopening for all callers."],
    checkQuestion: "What fallback can checkout return while the optional service is unhealthy?",
    prompt: "Which resilience behavior is appropriate?",
    choices: defineChoices("a", [
      ["Use a short timeout, open a circuit after failures, and return no recommendations", "The breaker stops repeated waits and preserves the required checkout path.", "Capacity recovers while controlled probes detect dependency recovery."],
      ["Retry indefinitely until recommendations return", "Unbounded retries consume all request capacity.", "An optional outage becomes a checkout outage."],
      ["Increase every timeout to one minute", "Longer waits retain more threads during the same failure.", "Resource exhaustion worsens."],
      ["Fail checkout immediately whenever recommendations fail", "The dependency is explicitly optional.", "Availability is reduced without a business need."],
    ]),
    difficulty: "intermediate",
    rationale: "Because recommendations are optional and are exhausting shared capacity, bounded timeouts plus a circuit breaker and empty fallback isolate the dependency failure.",
  }),
  defineQuestion({
    id: "q_design_04",
    categoryId: "software_design",
    subtopicId: "maintainability",
    conceptId: "concept_design_provider_boundary",
    sourceId,
    scenario: "Business code imports VendorMail SDK types in 40 files. A contract requires switching providers in three months without changing notification policies or tests.",
    caseType: "debugging_performance",
    decisionCriteria: ["Keep provider-specific APIs at one adapter boundary owned by the application."],
    practicalNotes: ["Model only capabilities the domain needs; do not reproduce the entire vendor SDK behind an interface."],
    checkQuestion: "Which layer should translate domain messages into vendor requests?",
    prompt: "What refactor best supports the provider swap?",
    choices: defineChoices("d", [
      ["Upgrade the current SDK in every file", "An upgrade keeps business code coupled to vendor types.", "The eventual swap still touches 40 files."],
      ["Wrap each vendor call with try/catch locally", "Error handling does not create a dependency boundary.", "Provider concepts continue leaking through the codebase."],
      ["Create a global function with the same vendor parameters", "A thin alias preserves vendor-shaped coupling.", "Tests and callers still depend on the old API."],
      ["Define a domain NotificationPort and implement VendorMail in one adapter", "The application-owned port expresses stable notification needs and isolates translation.", "A new adapter can replace the provider without policy changes."],
    ]),
    difficulty: "intermediate",
    rationale: "The planned provider swap and widespread vendor types call for dependency inversion: a narrow domain port with one infrastructure adapter.",
  }),
  defineQuestion({
    id: "q_design_05",
    categoryId: "software_design",
    subtopicId: "maintainability",
    conceptId: "concept_design_schema_ownership",
    sourceId,
    scenario: "Billing reads columns directly from Orders' private database. Orders needs to split address fields, but five Billing queries and deployments must change in lockstep.",
    caseType: "maintainability_safety",
    decisionCriteria: ["Let Orders evolve storage independently while publishing a stable consumer contract."],
    practicalNotes: ["Version the published contract and use consumer tests before removing old fields."],
    checkQuestion: "Who should own the external representation of order data?",
    prompt: "Which boundary reduces the coupling?",
    choices: defineChoices("b", [
      ["Grant Billing write access to the Orders tables", "More direct access increases coupling and data ownership ambiguity.", "Billing can corrupt Orders invariants."],
      ["Have Orders publish a versioned API or event schema owned by Orders", "Orders translates private storage into a stable external contract.", "Internal column changes no longer force Billing deployment."],
      ["Copy the shared SQL into a common package", "Shared queries preserve dependency on private columns.", "A schema change still breaks all consumers."],
      ["Freeze the Orders database forever", "Permanent schema immobility blocks required evolution.", "Maintenance cost moves into workarounds."],
    ]),
    difficulty: "intermediate",
    rationale: "The lockstep changes come from sharing private storage, so an Orders-owned API/event contract separates external semantics from internal schema.",
  }),
  defineQuestion({
    id: "q_design_06",
    categoryId: "software_design",
    subtopicId: "maintainability",
    conceptId: "concept_design_rule_of_three",
    sourceId,
    scenario: "One checkout flow has a 12-line tax calculation. No second caller exists, tax rules are still changing weekly, and the proposed generic rule engine would add four abstractions.",
    caseType: "basic_application",
    decisionCriteria: ["Avoid speculative abstraction until stable variation and reuse are observed."],
    practicalNotes: ["Keep the calculation named and tested locally so later extraction is safe when a second real case appears."],
    checkQuestion: "What evidence for a generic rule engine is missing?",
    prompt: "What should the team do now?",
    choices: defineChoices("a", [
      ["Keep the code local, clarify its name, and test current rules", "One changing use case does not yet reveal a stable reusable interface.", "Delivery stays simple and future refactoring remains protected."],
      ["Build the generic rule engine immediately", "The abstraction guesses at variation before evidence exists.", "Weekly changes spread across extra layers."],
      ["Duplicate the calculation into three unused modules", "Artificial duplication does not create real requirements.", "Maintenance burden increases without consumers."],
      ["Remove tests until the rules stabilize", "Changing rules make regression tests more valuable.", "Refactoring and policy changes become unsafe."],
    ]),
    difficulty: "beginner",
    rationale: "With one caller and volatile rules, the correct design is a well-tested local implementation rather than a speculative multi-layer abstraction.",
  }),
  defineQuestion({
    id: "q_design_07",
    categoryId: "software_design",
    subtopicId: "tradeoffs",
    conceptId: "concept_design_read_model",
    sourceId,
    scenario: "Orders must remain transactionally normalized for updates. A dashboard joins eight tables for every refresh, tolerates 60 seconds of staleness, and consumes most database CPU.",
    caseType: "common_failure",
    decisionCriteria: ["Preserve normalized write invariants while optimizing a stale-tolerant read path."],
    practicalNotes: ["Track read-model lag and rebuild it from authoritative events or change data when needed."],
    checkQuestion: "Which workload explicitly permits an eventually updated representation?",
    prompt: "Which design addresses the bottleneck without weakening order writes?",
    choices: defineChoices("d", [
      ["Denormalize the authoritative order tables for every dashboard column", "Changing write storage risks transactional invariants for a read-only need.", "Updates become complex and inconsistent."],
      ["Run the eight-table join more often", "Higher frequency increases the measured CPU problem.", "Dashboard load grows."],
      ["Remove foreign keys from Orders", "Constraints are not identified as the query bottleneck.", "Write integrity weakens without solving repeated joins."],
      ["Build a denormalized dashboard read model updated asynchronously", "A materialized projection serves the tolerated-stale query while normalized tables remain authoritative.", "Refresh cost moves out of each user request."],
    ]),
    difficulty: "advanced",
    rationale: "The dashboard accepts 60-second staleness and dominates read CPU, making an asynchronous denormalized read model appropriate while normalized writes retain invariants.",
  }),
  defineQuestion({
    id: "q_design_08",
    categoryId: "software_design",
    subtopicId: "tradeoffs",
    conceptId: "concept_design_sync_vs_queue",
    sourceId,
    scenario: "An internal thumbnail request takes 80 ms, callers need the thumbnail URL before continuing, volume is 20 per minute, and failure should be shown immediately rather than retried later.",
    caseType: "design_tradeoff",
    decisionCriteria: ["Prefer simple synchronous control flow when latency, volume, and immediate failure semantics permit it."],
    practicalNotes: ["Revisit a queue if processing becomes slow, bursty, retryable, or independent of the response."],
    checkQuestion: "Which stated requirement conflicts with returning before processing completes?",
    prompt: "Should the first version use a durable queue?",
    choices: defineChoices("c", [
      ["Yes, because every service call requires a queue", "Queues are a trade-off, not a universal requirement.", "The system gains operational machinery without need."],
      ["Yes, and return success before processing", "Callers require the URL and immediate failure outcome.", "The API would report success without its required result."],
      ["No; make a bounded synchronous call and return its URL or error", "The fast low-volume operation fits the caller's immediate dependency.", "The implementation stays simple and preserves failure semantics."],
      ["No; run it in an untracked background promise", "Untracked work can be lost and still cannot supply the URL.", "Callers proceed without the required result."],
    ]),
    difficulty: "beginner",
    rationale: "All constraints favor synchronous execution: low latency and volume, a required immediate result, and no later retry expectation.",
  }),
  defineQuestion({
    id: "q_design_09",
    categoryId: "software_design",
    subtopicId: "distributed_systems",
    conceptId: "concept_design_transactional_outbox",
    sourceId,
    scenario: "Creating an invoice commits to MySQL, then publishes invoice_created to a broker. A crash between the two operations leaves a committed invoice that downstream accounting never sees.",
    caseType: "debugging_performance",
    decisionCriteria: ["Atomically record business state and publication intent without requiring a distributed transaction."],
    practicalNotes: ["Make consumers idempotent because an outbox relay can publish a row more than once."],
    checkQuestion: "Which two writes must share the local database transaction?",
    prompt: "Which pattern closes the crash gap?",
    choices: defineChoices("a", [
      ["Insert the invoice and an outbox row in one transaction, then relay unpublished rows", "The local commit contains both state and durable publication intent.", "A relay resumes after crashes until downstream receives the event."],
      ["Publish before committing the invoice", "A crash or rollback can expose an event for nonexistent state.", "Downstream acts on an invoice that never committed."],
      ["Retry broker publish only in process memory", "A restart loses pending retry state.", "The stated crash still drops the event."],
      ["Ignore rare crashes and reconcile manually", "The requirement is reliable accounting notification.", "Silent omissions accumulate into financial inconsistency."],
    ]),
    difficulty: "advanced",
    rationale: "The failure lies between two systems, so a transactional outbox moves publication intent into the same MySQL transaction and lets a relay retry safely.",
  }),
  defineQuestion({
    id: "q_design_10",
    categoryId: "software_design",
    subtopicId: "tradeoffs",
    conceptId: "concept_design_modular_monolith",
    sourceId,
    scenario: "Eight engineers own one product, deploy weekly as one unit, and have no independent scaling needs. The codebase has tangled modules, but the team can run one reliable deployment pipeline.",
    caseType: "maintainability_safety",
    decisionCriteria: ["Improve ownership boundaries without adding distributed operations unsupported by team or scaling constraints."],
    practicalNotes: ["Enforce module APIs and dependency direction so a future service extraction remains possible if evidence appears."],
    checkQuestion: "Which missing requirement would justify an independently deployed service?",
    prompt: "What architecture change is proportionate now?",
    choices: defineChoices("d", [
      ["Split every module into a microservice", "No independent scaling or deployment need justifies network boundaries.", "Eight engineers inherit many services and failure modes."],
      ["Keep tangled dependencies because deployment works", "A working pipeline does not solve ownership and maintainability problems.", "Changes continue causing cross-module regressions."],
      ["Create one repository per source directory", "Repository layout alone does not enforce runtime or dependency boundaries.", "Coupling remains while workflows fragment."],
      ["Refactor to a modular monolith with explicit APIs and ownership", "Module boundaries target the observed tangling within the proven single-deploy model.", "Maintainability improves without distributed-system overhead."],
    ]),
    difficulty: "intermediate",
    rationale: "The problem is internal coupling, while team size, deployment, and scaling all favor one process; explicit modular-monolith boundaries are the proportional response.",
  }),
];
