import type { ReviewedQuestion } from "@/lib/quiz/content/types";
import { defineChoices, defineQuestion } from "@/lib/quiz/content/questions/helpers";


export const webBackendQuestions: ReviewedQuestion[] = [
  defineQuestion({
    id: "q_web_01",
    categoryId: "web_backend",
    subtopicId: "http",
    conceptId: "concept_web_idempotent_retry",
    scenario: "A client times out after sending an order-status update. It cannot tell whether the server committed the request, and retrying must not apply the transition twice.",
    caseType: "basic_application",
    decisionCriteria: ["Make the repeated request converge on one state and reuse a stable operation identity."],
    practicalNotes: ["Persist the idempotency result long enough to cover the client's retry window."],
    checkQuestion: "What server state lets a repeated request return the first result?",
    prompt: "Which HTTP design makes the retry safe?",
    choices: defineChoices("c", [
      ["POST a new transition with a fresh key on every attempt", "A fresh identity makes each retry look like a new operation.", "The transition can be applied more than once."],
      ["Retry only when the client process has restarted", "Client timing does not prove whether the server committed.", "Duplicate effects remain possible after ambiguous failures."],
      ["PUT the desired state with one idempotency key reused across attempts", "PUT expresses a target state and the stable key deduplicates the ambiguous retry.", "Repeated delivery returns the recorded result without a second transition."],
      ["Send the update as a GET request", "GET is defined as safe and should not mutate server state.", "Caches or crawlers could trigger an invalid side effect."],
    ]),
    difficulty: "intermediate",
    rationale: "An ambiguous timeout requires replay safety; a target-state PUT plus a persisted idempotency key handles both HTTP semantics and duplicate delivery.",
  }),
  defineQuestion({
    id: "q_web_02",
    categoryId: "web_backend",
    subtopicId: "http",
    conceptId: "concept_web_etag_revalidation",
    scenario: "A product document is read often, changes a few times per hour, and clients may reuse cached bytes only after checking that they are current.",
    caseType: "design_tradeoff",
    decisionCriteria: ["Avoid retransmitting unchanged bodies while revalidating every reuse."],
    practicalNotes: [
      "Send Cache-Control: no-cache with a stable ETag generated from the selected representation, including content encoding variants.",
    ],
    checkQuestion: "Which status tells the client to keep its cached body?",
    prompt: "Which cache policy meets the freshness constraint?",
    choices: defineChoices("a", [
      ["Cache-Control: max-age=86400 without validation", "A day-long fresh lifetime permits stale reuse without contacting the server.", "Clients can display data long after an update."],
      ["Cache-Control: no-store", "No-store prevents retaining the response at all.", "Every read retransmits the full body."],
      ["Add a random ETag on every response", "An unstable validator never matches unchanged content.", "Revalidation always downloads the body."],
      ["Send Cache-Control: no-cache with a stable ETag and require If-None-Match revalidation", "no-cache requires validation before reuse, and a matching stable validator allows a 304 response.", "Unchanged content saves bandwidth while every reuse is checked and updates are fetched promptly."],
    ], "d"),
    difficulty: "intermediate",
    rationale: "Cache-Control: no-cache requires validation before reuse; a stable ETag carried by If-None-Match lets unchanged content return 304 without retransmitting the body.",
  }),
  defineQuestion({
    id: "q_web_03",
    categoryId: "web_backend",
    subtopicId: "apis",
    conceptId: "concept_web_contract_first",
    scenario: "Web and API teams must develop in parallel for six weeks. The endpoint path, request validation, response schema, and error codes must be testable before either implementation is complete.",
    artifacts: [{
      kind: "api",
      title: "Contract requirement",
      language: "yaml",
      content: "POST /v1/invoices\nrequest: InvoiceCreate\nresponses:\n  201: Invoice\n  422: ValidationProblem",
    }],
    caseType: "maintainability_safety",
    decisionCriteria: ["Provide one machine-readable boundary for mocks, validation, and compatibility tests."],
    practicalNotes: ["Version the contract and run producer plus consumer checks in CI."],
    checkQuestion: "What artifact can both teams use without importing each other's code?",
    prompt: "What should the teams agree on first?",
    choices: defineChoices("d", [
      ["A versioned OpenAPI contract with schemas and errors", "The explicit contract supports generated mocks and independent conformance tests.", "Both teams can build in parallel against the same boundary."],
      ["The API team's internal ORM models", "Persistence models omit protocol details and couple clients to storage.", "Frontend work blocks on backend implementation choices."],
      ["A shared chat thread describing examples", "Prose examples are not exhaustive or machine-verifiable.", "Validation and error behavior drift between teams."],
      ["Agree on example payloads, then formalize the contract after both implementations finish", "Examples help discussion but do not provide the requested early validation or complete error schema.", "The teams discover incompatible assumptions at integration time."],
    ], "a"),
    difficulty: "intermediate",
    rationale: "Parallel implementation requires a machine-checkable protocol artifact; the specified path, schemas, and errors belong in a versioned API contract.",
  }),
  defineQuestion({
    id: "q_web_04",
    categoryId: "web_backend",
    subtopicId: "apis",
    conceptId: "concept_web_backward_compatible_response",
    scenario: "Existing mobile clients deserialize known JSON fields and ignore unknown fields. They cannot all upgrade this quarter, but new clients need an estimatedDelivery field.",
    caseType: "common_failure",
    decisionCriteria: ["Preserve the meaning and types of all existing required response fields."],
    practicalNotes: ["Contract-test old client fixtures before release even when the change is expected to be additive."],
    checkQuestion: "Which change can an existing client safely ignore?",
    prompt: "Which response evolution is backward compatible under these client rules?",
    choices: defineChoices("c", [
      ["Rename the required deliveryDate field", "Old clients still request the old name and see it missing.", "Existing delivery screens break."],
      ["Add a new optional estimatedDelivery field", "Unknown optional output is ignored by the stated old clients.", "New clients gain the value while existing clients keep working."],
      ["Change orderId from a string to a number", "Changing an existing field type violates the deserializer contract.", "Older clients reject or misread responses."],
      ["Remove the required status field", "Clients may branch on status today.", "Existing flows lose required data."],
    ], "b"),
    difficulty: "beginner",
    rationale: "The scenario explicitly guarantees unknown response fields are ignored, making an optional additive field compatible while renames, removals, and type changes break existing clients.",
  }),
  defineQuestion({
    id: "q_web_05",
    categoryId: "web_backend",
    subtopicId: "authentication",
    conceptId: "concept_web_first_party_session",
    scenario: "A first-party browser app and same-site backend are operated together. The team needs immediate logout, server-side revocation, and protection from JavaScript reading credentials.",
    caseType: "design_tradeoff",
    decisionCriteria: ["Prefer revocable server state and an HttpOnly browser credential."],
    practicalNotes: ["Use Secure, SameSite, CSRF protection, rotation after login, and short idle expiry."],
    checkQuestion: "Which requirement favors a server-side session over a self-contained access token?",
    prompt: "Which authentication mechanism is the best default?",
    choices: defineChoices("b", [
      ["A bearer token stored in localStorage", "Page JavaScript can read localStorage after an XSS.", "Credential theft gives the attacker bearer access until expiry."],
      ["A permanent API key embedded in the bundle", "Every user receives the same extractable secret.", "One bundle inspection compromises the application credential."],
      ["An opaque server-side session ID in a Secure HttpOnly cookie", "The server can revoke the session immediately and JavaScript cannot read the cookie.", "Logout and incident response invalidate access centrally."],
      ["A long-lived self-contained token with no revocation list", "Immediate revocation is not available before token expiry.", "Logged-out or compromised tokens remain usable."],
    ], "c"),
    difficulty: "intermediate",
    rationale: "Same-site first-party operation removes cross-client token needs, while immediate revocation and JavaScript isolation directly favor an opaque HttpOnly session cookie.",
  }),
  defineQuestion({
    id: "q_web_06",
    categoryId: "web_backend",
    subtopicId: "authentication",
    conceptId: "concept_web_oauth_state_pkce",
    scenario: "A public browser client uses an OAuth authorization-code flow. It cannot keep a client secret, and login responses must be bound to the browser that initiated them.",
    caseType: "common_failure",
    decisionCriteria: ["Prevent callback login CSRF and intercepted-code redemption without a client secret."],
    practicalNotes: ["Store state and the PKCE verifier in the initiating browser session and consume each once."],
    checkQuestion: "Which value binds the callback, and which value binds code redemption?",
    prompt: "Which controls are required?",
    choices: defineChoices("d", [
      ["A client secret shipped in JavaScript", "A public client cannot keep a bundled secret confidential.", "Anyone can extract and reuse the supposed secret."],
      ["Only an exact redirect URI", "Redirect matching does not bind the callback to an initiating browser or code verifier.", "Login CSRF and code interception risks remain."],
      ["Only a SameSite cookie", "Cookie policy alone does not prove OAuth response correlation or PKCE possession.", "An unsolicited callback can still be accepted."],
      ["A one-time state value plus PKCE S256", "State correlates the callback and PKCE requires the original verifier to redeem the code.", "Both browser binding and intercepted-code protection are enforced."],
    ]),
    difficulty: "advanced",
    rationale: "The two stated threats are distinct: one-time state provides request correlation, while PKCE S256 replaces an unkeepable public-client secret for code redemption.",
  }),
  defineQuestion({
    id: "q_web_07",
    categoryId: "web_backend",
    subtopicId: "caching",
    conceptId: "concept_web_cache_invalidation",
    scenario: "GET /profiles/42 is cached for ten minutes. After PATCH /profiles/42 commits, the next read must return the new display name, including from other application instances.",
    caseType: "basic_application",
    decisionCriteria: ["Coordinate invalidation after the durable write succeeds and across all instances."],
    practicalNotes: ["Use versioned keys or delete the shared cache key only after commit to avoid exposing uncommitted data."],
    checkQuestion: "Why must invalidation happen after the database commit?",
    prompt: "What should the write path do?",
    choices: defineChoices("a", [
      ["Commit the database update, then invalidate the shared profile key", "Post-commit invalidation makes subsequent misses reload durable new data across instances.", "The next read observes the updated display name."],
      ["Update only the writer's in-process cache", "Other instances retain the old value.", "Users see inconsistent profiles depending on routing."],
      ["Wait for the ten-minute TTL", "The explicit next-read freshness requirement forbids stale reuse.", "Old data remains visible after a successful edit."],
      ["Invalidate before attempting the database write", "A concurrent miss can repopulate the old committed value before the write completes.", "The cache can remain stale even after the update succeeds."],
    ]),
    difficulty: "intermediate",
    rationale: "Cross-instance next-read freshness requires invalidating the shared key, and doing so after commit ensures any refill reads the durable new value.",
  }),
  defineQuestion({
    id: "q_web_08",
    categoryId: "web_backend",
    subtopicId: "caching",
    conceptId: "concept_web_cache_stampede",
    scenario: "A popular report key expires hourly. Ten thousand requests arrive within one second, while regeneration takes five seconds and overloads the database if performed concurrently.",
    caseType: "debugging_performance",
    decisionCriteria: ["Allow one regeneration while serving bounded stale data or waiting callers."],
    practicalNotes: ["Add TTL jitter across keys and give the regeneration lock a safe expiry."],
    checkQuestion: "How many callers should execute the expensive regeneration?",
    prompt: "Which design prevents the stampede?",
    choices: defineChoices("c", [
      ["Let every cache miss regenerate independently", "All ten thousand misses hit the expensive path together.", "The database overload repeats at each expiry."],
      ["Use single-flight regeneration with stale-while-revalidate", "One owner refreshes while other callers reuse bounded stale data.", "Load stays controlled and most callers avoid a five-second wait."],
      ["Shorten the TTL to one minute", "More frequent synchronized expiry increases regeneration opportunities.", "The stampede becomes more frequent."],
      ["Remove the cache", "Every request then executes the expensive report query.", "Database load becomes continuously unsustainable."],
    ], "b"),
    difficulty: "advanced",
    rationale: "The failure is concurrent regeneration of one hot key, so single-flight ownership directly limits work while stale-while-revalidate preserves availability.",
  }),
  defineQuestion({
    id: "q_web_09",
    categoryId: "web_backend",
    subtopicId: "async_processing",
    conceptId: "concept_web_durable_side_effect",
    scenario: "Checkout must respond within 300 ms after committing the order. Sending a receipt sometimes takes eight seconds, must survive process restarts, and may be retried.",
    caseType: "debugging_performance",
    decisionCriteria: ["Keep the user transaction fast while durably recording the eventual side effect."],
    practicalNotes: ["Enqueue transactionally with the order or use an outbox so a commit cannot lose the receipt job."],
    checkQuestion: "What must be durable before checkout reports success?",
    prompt: "Where should receipt sending happen?",
    choices: defineChoices("d", [
      ["Inside the checkout request before committing", "The eight-second call exceeds the response budget and holds transaction resources.", "Checkout times out even when the order could be accepted."],
      ["In a detached in-memory promise after response", "Process exit can drop the untracked promise.", "Committed orders sometimes never receive receipts."],
      ["In a durable queued job consumed after commit", "The queue decouples response latency and retains work through restarts.", "Checkout stays fast and receipt delivery can retry."],
      ["In the browser after payment", "The client may close and cannot be trusted with server receipt credentials.", "Delivery becomes unreliable and exposes privileged behavior."],
    ], "c"),
    difficulty: "intermediate",
    rationale: "The side effect is slow, retryable, and must survive restarts, so it belongs behind a durable enqueue that is coupled safely to the committed order.",
  }),
  defineQuestion({
    id: "q_web_10",
    categoryId: "web_backend",
    subtopicId: "async_processing",
    conceptId: "concept_web_idempotent_consumer",
    scenario: "A broker provides at-least-once delivery. The same payment_captured event may arrive twice after a worker crashes between charging a ledger entry and acknowledging the message.",
    caseType: "maintainability_safety",
    decisionCriteria: ["Make event replay produce one ledger effect without relying on exactly-once delivery."],
    practicalNotes: ["Record the event ID and ledger mutation in the same database transaction."],
    checkQuestion: "What happens if the worker crashes after commit but before acknowledgement?",
    prompt: "How should the consumer handle redelivery?",
    choices: defineChoices("b", [
      ["Acknowledge before writing the ledger", "A crash after acknowledgement loses an uncommitted event.", "The payment can disappear from the ledger."],
      ["Assume the broker never duplicates a message", "At-least-once delivery explicitly permits redelivery.", "Duplicate ledger entries occur during normal recovery."],
      ["Deduplicate only in process memory", "Restart clears the seen-event set.", "The crash scenario still applies the event twice."],
      ["Transactionally insert the event ID with a unique constraint and the ledger row", "A duplicate event conflicts with the persisted ID and skips a second effect.", "Redelivery is safe even across worker crashes."],
    ], "d"),
    difficulty: "advanced",
    rationale: "The acknowledged failure window is unavoidable with at-least-once delivery, so a durable unique event ID committed atomically with the ledger effect supplies idempotency.",
  }),
];
