/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env preview --env-interface CloudflareEnv --include-runtime false cloudflare-env.d.ts` (hash: c3cf22fc32259681c47539a3317103be)
declare namespace Cloudflare {
	interface Env {
		PODCAST_AUDIO: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
