export type LearningSource = {
  id: string;
  categoryId: string;
  subtopicId: string;
  title: string;
  url: string;
  conceptSynopsis: string;
};

export const learningSources = [
  {
    id: "source_cs_data_structures",
    categoryId: "cs_foundations",
    subtopicId: "data_structures",
    title: "MIT 6.006 Data Structures Notes",
    url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/pages/lecture-notes/",
    conceptSynopsis: "Data structures organize values around required operations, trading memory, ordering guarantees, and lookup or update cost.",
  },
  {
    id: "source_cs_algorithms",
    categoryId: "cs_foundations",
    subtopicId: "algorithms",
    title: "MIT 6.006 Algorithms Resource Index",
    url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/pages/resource-index/",
    conceptSynopsis: "Algorithm analysis compares how time and space grow with input size so production choices remain viable beyond small benchmarks.",
  },
  {
    id: "source_cs_operating_systems",
    categoryId: "cs_foundations",
    subtopicId: "operating_systems",
    title: "Node.js Event Loop and Worker Pool",
    url: "https://nodejs.org/en/learn/asynchronous-work/dont-block-the-event-loop",
    conceptSynopsis: "Processes, event loops, and durable external state have different isolation and failure properties that shape concurrency decisions.",
  },
  {
    id: "source_cs_networking",
    categoryId: "cs_foundations",
    subtopicId: "networking",
    title: "IETF Internet Host Requirements",
    url: "https://www.rfc-editor.org/rfc/rfc1122.html",
    conceptSynopsis: "Network failures occur at distinct naming, transport, TLS, and application layers, so evidence should localize the failing boundary.",
  },
  {
    id: "source_cs_databases",
    categoryId: "cs_foundations",
    subtopicId: "databases",
    title: "MySQL Index Optimization",
    url: "https://dev.mysql.com/doc/refman/8.4/en/optimization-indexes.html",
    conceptSynopsis: "Database indexes accelerate selected read paths by maintaining additional ordered data, with storage and write-amplification costs.",
  },
  {
    id: "source_web_http",
    categoryId: "web_backend",
    subtopicId: "http",
    title: "RFC 9110 HTTP Semantics",
    url: "https://www.rfc-editor.org/rfc/rfc9110.html",
    conceptSynopsis: "HTTP methods, validators, and cache directives communicate retry, freshness, and conditional-request semantics across intermediaries.",
  },
  {
    id: "source_web_apis",
    categoryId: "web_backend",
    subtopicId: "apis",
    title: "OpenAPI Specification",
    url: "https://spec.openapis.org/oas/",
    conceptSynopsis: "An API contract makes requests, responses, errors, and compatibility expectations explicit for independently developed clients and servers.",
  },
  {
    id: "source_web_authentication",
    categoryId: "web_backend",
    subtopicId: "authentication",
    title: "OAuth 2.0 Security Best Current Practice",
    url: "https://www.rfc-editor.org/rfc/rfc9700.html",
    conceptSynopsis: "Authentication designs bind credentials and authorization responses to the intended client while limiting theft, replay, and revocation risk.",
  },
  {
    id: "source_web_caching",
    categoryId: "web_backend",
    subtopicId: "caching",
    title: "AWS Caching Data Access Patterns",
    url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/perf_data_access_patterns_caching.html",
    conceptSynopsis: "Application caches reduce origin work only when invalidation, expiry, concurrency, and cross-instance consistency match the freshness requirement.",
  },
  {
    id: "source_web_async_processing",
    categoryId: "web_backend",
    subtopicId: "async_processing",
    title: "RabbitMQ Reliability Guide",
    url: "https://www.rabbitmq.com/docs/reliability",
    conceptSynopsis: "Durable asynchronous work separates request latency from background effects and assumes messages can be retried or delivered more than once.",
  },
  {
    id: "source_frontend_typescript",
    categoryId: "frontend",
    subtopicId: "typescript",
    title: "TypeScript 4.9: satisfies Operator",
    url: "https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html",
    conceptSynopsis: "TypeScript can preserve precise inference while checking conformance, but untrusted runtime data still needs runtime validation.",
  },
  {
    id: "source_frontend_browsers",
    categoryId: "frontend",
    subtopicId: "browsers",
    title: "MDN Web Performance Guide",
    url: "https://developer.mozilla.org/en-US/docs/Web/Performance",
    conceptSynopsis: "Browser behavior combines a main-thread event loop, platform security controls, rendering work, and client-specific presentation decisions.",
  },
  {
    id: "source_frontend_state",
    categoryId: "frontend",
    subtopicId: "state_management",
    title: "React: Choosing the State Structure",
    url: "https://react.dev/learn/choosing-the-state-structure",
    conceptSynopsis: "State belongs at the narrowest durable owner that matches its lifecycle, while remote data needs explicit loading, caching, and race handling.",
  },
  {
    id: "source_frontend_accessibility",
    categoryId: "frontend",
    subtopicId: "accessibility",
    title: "WAI-ARIA Authoring Practices",
    url: "https://www.w3.org/WAI/ARIA/apg/",
    conceptSynopsis: "Accessible interfaces expose native semantics, keyboard behavior, focus, and error relationships that assistive technology can understand.",
  },
  {
    id: "source_infrastructure_cloud",
    categoryId: "infrastructure",
    subtopicId: "cloud",
    title: "AWS Well-Architected Reliability Pillar",
    url: "https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/welcome.html",
    conceptSynopsis: "Cloud architecture allocates operational responsibility and recovery capacity according to explicit availability, RTO, and RPO requirements.",
  },
  {
    id: "source_infrastructure_containers",
    categoryId: "infrastructure",
    subtopicId: "containers",
    title: "Docker Build Cache Guidance",
    url: "https://docs.docker.com/build/cache/invalidation/",
    conceptSynopsis: "Container images should be reproducible and layered deliberately, while runtime limits define the resources a process can actually consume.",
  },
  {
    id: "source_infrastructure_ci_cd",
    categoryId: "infrastructure",
    subtopicId: "ci_cd",
    title: "SLSA Build Requirements",
    url: "https://slsa.dev/spec/v1.2/build-requirements",
    conceptSynopsis: "A delivery pipeline promotes reviewed immutable artifacts and sequences compatible application and data changes across live versions.",
  },
  {
    id: "source_infrastructure_observability",
    categoryId: "infrastructure",
    subtopicId: "observability",
    title: "OpenTelemetry Observability Primer",
    url: "https://opentelemetry.io/docs/concepts/observability-primer/",
    conceptSynopsis: "Traces, metrics, logs, and user-centered service objectives answer different operational questions and impose different cardinality costs.",
  },
  {
    id: "source_security_authorization",
    categoryId: "security",
    subtopicId: "authorization",
    title: "OWASP Authorization Cheat Sheet",
    url: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html",
    conceptSynopsis: "Authorization evaluates each requested action against trusted identity, role, tenant, and resource ownership at the server boundary.",
  },
  {
    id: "source_security_vulnerabilities",
    categoryId: "security",
    subtopicId: "vulnerabilities",
    title: "OWASP Top 10",
    url: "https://owasp.org/www-project-top-ten/",
    conceptSynopsis: "Injection, scripting, and request-forgery defenses keep untrusted input from changing query, markup, or authenticated action semantics.",
  },
  {
    id: "source_security_secrets",
    categoryId: "security",
    subtopicId: "secret_handling",
    title: "OWASP Secrets Management Cheat Sheet",
    url: "https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html",
    conceptSynopsis: "Secrets require centralized storage, least-privilege delivery, rotation, and incident handling without entering source code or image layers.",
  },
  {
    id: "source_security_supply_chain",
    categoryId: "security",
    subtopicId: "supply_chain",
    title: "SLSA Threats and Mitigations",
    url: "https://slsa.dev/spec/v1.2/threats",
    conceptSynopsis: "Supply-chain controls bind dependencies and artifacts to reviewed versions, trusted builders, provenance, and a practiced compromise response.",
  },
  {
    id: "source_design_distributed_systems",
    categoryId: "software_design",
    subtopicId: "distributed_systems",
    title: "Amazon Builders' Library: Distributed Systems Challenges",
    url: "https://aws.amazon.com/builders-library/challenges-with-distributed-systems/",
    conceptSynopsis: "Distributed components fail independently, so invariants rely on atomic authority, idempotency, bounded retries, and durable handoff.",
  },
  {
    id: "source_design_maintainability",
    categoryId: "software_design",
    subtopicId: "maintainability",
    title: "Azure Architecture Design Principles",
    url: "https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/",
    conceptSynopsis: "Maintainable boundaries isolate volatile providers and ownership while avoiding abstractions that have no demonstrated second use.",
  },
  {
    id: "source_design_tradeoffs",
    categoryId: "software_design",
    subtopicId: "tradeoffs",
    title: "AWS Well-Architected Framework Pillars",
    url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/the-pillars-of-the-framework.html",
    conceptSynopsis: "Architecture choices trade consistency, freshness, latency, operational cost, and organizational complexity against explicit product needs.",
  },
  {
    id: "source_ai_llms",
    categoryId: "ai_engineering",
    subtopicId: "llms",
    title: "OpenAI Model Optimization Guide",
    url: "https://developers.openai.com/api/docs/guides/model-optimization",
    conceptSynopsis: "LLM systems separate current context, output constraints, application validation, evaluation, and training-time behavior optimization.",
  },
  {
    id: "source_ai_rag",
    categoryId: "ai_engineering",
    subtopicId: "rag",
    title: "OpenAI Retrieval Guide",
    url: "https://developers.openai.com/api/docs/guides/retrieval",
    conceptSynopsis: "Retrieval quality depends on document structure, metadata, query construction, ranking, and evidence traces before generation begins.",
  },
  {
    id: "source_ai_agents",
    categoryId: "ai_engineering",
    subtopicId: "agents",
    title: "OpenAI Safety in Building Agents",
    url: "https://developers.openai.com/api/docs/guides/agent-builder-safety",
    conceptSynopsis: "Agents need bounded budgets, least-privilege tools, progress checks, and human approval around consequential or irreversible effects.",
  },
  {
    id: "source_ai_mcp",
    categoryId: "ai_engineering",
    subtopicId: "mcp",
    title: "Model Context Protocol Tools Specification",
    url: "https://modelcontextprotocol.io/specification/2025-11-25/server/tools",
    conceptSynopsis: "MCP exposes typed capabilities across a trust boundary, so clients and servers must validate inputs, outputs, permissions, and tool intent.",
  },
  {
    id: "source_ai_evaluation",
    categoryId: "ai_engineering",
    subtopicId: "evaluation",
    title: "OpenAI Evals Guide",
    url: "https://developers.openai.com/api/docs/guides/evals",
    conceptSynopsis: "Representative held-out evaluations turn model or prompt changes into measurable regressions against explicit release thresholds.",
  },
  {
    id: "source_ai_safety",
    categoryId: "ai_engineering",
    subtopicId: "safety",
    title: "OpenAI Safety Best Practices",
    url: "https://developers.openai.com/api/docs/guides/safety-best-practices",
    conceptSynopsis: "AI safety minimizes data and authority, separates instructions from untrusted content, and adds validation before external effects.",
  },
] as const satisfies readonly LearningSource[];

const learningSourceBySubtopic = new Map(
  learningSources.map((source) => [
    `${source.categoryId}:${source.subtopicId}`,
    source,
  ]),
);

export function getLearningSource(categoryId: string, subtopicId: string): LearningSource {
  const source = learningSourceBySubtopic.get(`${categoryId}:${subtopicId}`);
  if (!source) throw new Error(`learning_source_missing:${categoryId}:${subtopicId}`);
  return source;
}
